### ISSUE TITLE
Feature request - Reduce Stream to mono option

### ISSUE THREAD

**Issue by christi-ko** [schreibfaul1/ESP32-audioI2S#100]
Hi Wolle,

first of all big thanks to provide this library. Up to now i used your VS1053 library for my Radio project but yesterday i burned my VS1053 and so i changed today to a pcm5102 which i had available. However for the VS1053 i found a way to write to a register to have MONO output (would be a nice option there too). 

Since i only use one amplifier and one box in my project it would be good to have mono output on one of the channels of the pcm5102. Is there a way to have mono or can it be integrated in some way?

regards
Christian

**Comment by schreibfaul1** [comment]
Hi Christian,
This is a good option. From the sum signal (left + right) I created the mean value, which is placed as a mono signal on both channels. You can call up the mono option with  audio.forceMono(true); // default is false
