### ISSUE TITLE
usb flash support

### ISSUE THREAD

**Issue by clear-sky** [schreibfaul1/ESP32-audioI2S#101]
hi 
thanks for your great work!
if possible please add support ch376s for playing files in usb flash drives
https://github.com/djuseeq/Ch376msc

**Comment by schreibfaul1** [comment]
It is better to give the external drive an object name e.g. USB and then to call the function audio.connecttoFS (USB, 'myFile.mp3');

**Comment by clear-sky** [comment]
thanks for answer
but i am not expert
will be thankful if you give me a simple sketch
thanks for your notice
