### ISSUE TITLE
About different languages

### ISSUE THREAD

**Issue by SyXavier** [schreibfaul1/ESP32-audioI2S#102]
Hi, schreibfaul1. Song names in different languages such as Chinese, Janpanese, Korean...SD.open() can't recognize file names. I tried to convert them into ASCII codes, but they still can't be recognized. Is there any way to solve it?

**Comment by schreibfaul1** [comment]
That's the discussion like # 86. How the file names are interpreted depends on the CODEPAGE in sdkconfig.h. Unfortunately UTF-8 is not used for the SD card. Up to now I had built in a conversion for Western Europe, which is now only effective for the CP 850. Chinese, Japanese ... remains unchanged now.
