### ISSUE TITLE
I2S Audio in Esphome

### ISSUE THREAD

**Issue by timotoots** [schreibfaul1/ESP32-audioI2S#107]
It seems there is a need for audio library in Esphome project. Could this library be used in esphome?

https://github.com/esphome/feature-requests/issues/599

**Comment by timotoots** [comment]
I have read little bit more about Esphome and it seems it would be fairly easy to create a custom component in Esphome if this library would be accessible in Platformio. Any chance this could happen?

**Comment by rarroyo6** [comment]
This is something I've been looking for. It would be great to play audio from HA in cheap ESP speakers.
Specially applicable to TTS, where HA does all the processing and the ESP just plays the received URL.
