### ISSUE TITLE
Unable to start a new stream in audio_eof_stream event

### ISSUE THREAD

**Issue by dingdinghzq** [schreibfaul1/ESP32-audioI2S#112]
I'd like to have a list of web url and want to play them one by one.
However,  in audio.cpp, after doing audio_eof_stream() callback, the library calls stopSong(), which prevent users to connect to next audio station. 
It should be a simple fix to switch the order of stopSong() and audio_eof_stream, but not sure if that breaks anything.

**Comment by schreibfaul1** [comment]
You are right, stopSong () must not come after callback, but first stopSong () and then callback. Thank you for the valuable tip.
