### ISSUE TITLE
Get control back with problematic webstream

### ISSUE THREAD

**Issue by biologist79** [schreibfaul1/ESP32-audioI2S#114]
HI,

it's me again, the ESPuino-guy (recently had to rename my projec coming from Tonuinot) :-) However, got a question to you - it's not really a bug.

Got your ESP32-audioI2S running in a dedicated task. Now the communication with this task is primarily done by queues (next track, prev. track, different playlist, vol+, vol-...). This runs fine. But the problem is: it only works, when ESP32-audioI2S is cooperative. So guess there's a webstream that's lagging, sometimes there's no way to get control back (unless I do a restart). Meaning: I can fill the queue with stuff, but ESP32-audioI2S doesn't respond to commands.

Is there a way to tell ESP32-audioI2S to do a restart/retry of that what's currently doing? Or maybe stopping and returning an error code?

Thanks in advance.

BR
Torsten.

**Comment by schreibfaul1** [comment]
Yes, that happens when the thread is stuck in the depths of the WiFi and only returns to the loop() after a delay or timeout. I leave the question open, maybe someone reading this has a good idea.
