### ISSUE TITLE
Change in sound quality after some seconds

### ISSUE THREAD

**Issue by christi-ko** [schreibfaul1/ESP32-audioI2S#127]
Hi Wolle,

sorry to directly open the next issue, but there is another strange behavior which i discovered with 2 streams i tried. 
1.) If i play one of the below shown streams, the sound quality seems to drop after about 3-5s playing. The sound is getting kind of dull (dumpf in deutsch). These are the only streams where i observed such kind of behavior.

>   "https://edge05.streamonkey.net/radio7-ravensburg"
  "https://edge05.streamonkey.net/radio7-rock"

2.) Additional note, not really a issue: The bitrate of this stream seems to be 0 for the AAC format. 

Here you can see the log of one of the mentioned streams. At the time where you could observe the change, no debug message shown for any change or similar.
> DEBUG:        buffers freed, free Heap: 186860 bytes
DEBUG:        Connect to new host: "https://edge05.streamonkey.net/radio7-ravensburg"
DEBUG:        Connect to "edge05.streamonkey.net" on port 443, extension "/radio7-ravensburg"
DEBUG:        SSL has been established, free Heap: 138976 bytes
DEBUG:        HTTP/1.0 200 OK
DEBUG:        access-control-allow-origin: *
DEBUG:        content-type: audio/aac, format is aac
DEBUG:        AACDecoder has been initialized, free Heap: 120572 bytes
DEBUG:        server: streaMonkey streaming Server Native
DEBUG:        sessionid: 6040133add9f1ed1d0599b56
DEBUG:        icy-audio-info: channels=2;samplerate=44100
DEBUG:        icy-description: Radio 7 Ravensburg
DEBUG:        icy-name: Radio 7 Ravensburg
DEBUG:        icy-url: https://www.radio7.de
DEBUG:        date: Wed, 03 Mar 2021 22:52:42 GMT
DEBUG:        Switch to DATA, metaint is 8192
DEBUG:        inputbuffer is being filled
DEBUG:        stream ready
DEBUG:        buffer filled in 235 ms
DEBUG:        syncword found at pos 0
DEBUG:        Channels: 2
DEBUG:        SampleRate: 22050
DEBUG:        BitsPerSample: 16
DEBUG:        BitRate: 100603
DEBUG:        AAC HeaderFormat: ADTS
DEBUG:        AAC Codec: MPEG-4
DEBUG:        AAC Profile: LowComplexity
DEBUG:        VBR recognized, audioFileDuration is estimated
DEBUG:        StreamTitle="TOM GRENNAN - LITTLE BIT OF LOVE"

**Comment by schreibfaul1** [comment]
Hi christi-ko,
you are absolutely right, the bit rate affects the quality of the sound. The bit rate is calculated for uncompressed files: _br = samprate * channels * bitspersample_. In the two examples, the br is extremely low. Is that why a lot of information is lost? Not necessarily. There is a process called SBR. This allows a large part of the audio information to be reconstructed. The AAC decoder can do that. Please open the aacdecoder.h and activate AAC_ENABLE_SBR at the top  and recompile. Then simply connect to the URL without "https: //" only "edge05.streamonkey.net/radio7-ravensburg" passed as a non-encrypted stream. The sound will be much better, theoretically better than mp3. However, the ESP32 will stick to its boundaries. I was too quick to suggest moving the SBR buffer to PSRAM, this is not possible.
PSRAM is an extra memory chip outside of the ESP32 and has access times that are too long via a bus system,
therefore, it takes too long to decode.
Bitrate = '' is still a relic from back then when I did not check the bitrate in the decoded stream could determine. I now have the option of calculating using the compression rate found.
I hope that makes some of the difficulties in finding a compromise clear between decoding time, memory consumption and sound quality.
