### ISSUE TITLE
Current playback position for MP3 

### ISSUE THREAD

**Issue by MichaelDworkin** [schreibfaul1/ESP32-audioI2S#136]
How do I find out the current playback position for MP3 playback ?
How can I play MP3 from a specific position or second?
I want to build an audio book player

**Comment by schreibfaul1** [comment]
Hi Michael,
with getAudioFileDuration() you can determine the total playing time of a file.
getAudioCurrentTime() returns the current playing time within the file.
setTimeOffset (int seconds) sets the time stamp forwards or backwards from the current position.
