### ISSUE TITLE
slow stream, dropouts are possible

### ISSUE THREAD

**Issue by yatatyork** [schreibfaul1/ESP32-audioI2S#137]
Hello Mr.
I can connecthost https://mp3.ffh.de/ffhplus/hq80er.mp3 
But when it print title and url about songs once 
then always show  "slow stream, dropouts are possible"  about 1minute then lost 
(WiFi connect Personal Hotspot)
Is it just poor Internet problem?
I will go to school and test school wifi
![1616685093373](https://user-images.githubusercontent.com/39113943/112496191-7ec45c80-8dbf-11eb-8edf-5385645a0d8b.jpg)
![1616685204847](https://user-images.githubusercontent.com/39113943/112496485-be8b4400-8dbf-11eb-967e-be56614c63bb.jpg)

**Comment by schreibfaul1** [comment]
It's the same with me too. Maybe a temporary problem or a bad connection. Please try http://mp3.ffh.de/ffhchannels/80er.aac
Radio Browser https://www.radio-browser.info/#!/ is a good address to find alternative URLs

**Comment by yatatyork** [comment]
Thank for your reply!
I will try it and report my result
