### ISSUE TITLE
Feature request - Simple DSP features

### ISSUE THREAD

**Issue by christi-ko** [schreibfaul1/ESP32-audioI2S#143]
I just sas while checking the code you implemented some kind of filtering in the code (i guess some kine of related to MONO and Stereo selection). Do you thing it's possible to have something like a adjustable high pass to remove low frequencies (e.g. below 50Hz) to reduce power consumption for not supported frequencies (if not already implemented). 
Are there enough resources left? The VS1053 includes some of these features already, but i guess they are done by the VS1053 itself.

**Comment by schreibfaul1** [comment]
Three digital filters are integrated (low, middle, high), by default, they have no function. With setTone (low, middle, high) frequency ranges can be lowered to -40dB or increased by + 6dB. The filter frequencies are set arbitrarily (0.5KHz, 3KHz, 6KHz), but can be changed. Important: When changing the sample rate, the filters must be recalculated. You can also chain several of the same filters for a steeper filter curve.
