### ISSUE TITLE
Just a question?

### ISSUE THREAD

**Issue by nodoubtman** [schreibfaul1/ESP32-audioI2S#171]
Hello. I just have one question.

What is the difference between audio I2S and vs1053 ?

thanks.
Marc.

**Comment by biologist79** [comment]
i2s is a protocol whereas vs1053 is a chip.
When using I2S with this lib, ESP32 has to decode the music in software, makes i2s of it and send it to an external dac. vs1053 in contrast decodes music in hardware and ESP32 only tells vs1053 what to do :)

**Comment by nodoubtman** [comment]
> 
> 
> i2s is a protocol whereas vs1053 is a chip.
> When using I2S with this lib, ESP32 has to decode the music in software, makes i2s of it and send it to an external dac. vs1053 in contrast decodes music in hardware and ESP32 only tells vs1053 what to do :)

Thank you for your time :)
good evening :)
Marc.

**Comment by nodoubtman** [comment]
thanks :)
