### ISSUE TITLE
feature request : Amazon Polly

### ISSUE THREAD

**Issue by deladriere** [schreibfaul1/ESP32-audioI2S#175]
Hi there
Thanks for this outstanding work!
Did you try to connect to Amazon Polly text to speech?
This would be really great!

**Comment by schreibfaul1** [comment]
As far as I know, Amazon Polly is only usable for users who have an AWS account. Google TTS is freely available

**Comment by deladriere** [comment]
Yes, sure but it's easy to get one
And there also IBM Watson with a free plan
