### ISSUE TITLE
Can't play mp3 example

### ISSUE THREAD

**Issue by namdv11** [schreibfaul1/ESP32-audioI2S#182]
![Capture](https://user-images.githubusercontent.com/88304168/128001491-9eb5565d-fb7c-40a0-8fe8-1253b07d248a.PNG)
I tried to play one mp3 file from "Testfiles" folder but it didn't work
Could you help me to fix it?

**Comment by schreibfaul1** [comment]
It looks as if githul is preventing larger files from being played from the server, then no "content-type: audio/mpeg" will be transmitted any more. It is still possible to copy these audio files to your own server.
