### ISSUE TITLE
Can't use other languages

### ISSUE THREAD

**Issue by SyXavier** [schreibfaul1/ESP32-audioI2S#190]
Hi, Wolle. Can't sdfat example use other languages?
----------------------------------------------------------------------------------------------------
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10864
load:0x40080400,len:6432
entry 0x400806b8
info        PSRAM found, inputBufferSize: 283615 bytes
info        buffers freed, free Heap: 312380 bytes
info        Reading file: "/蜀绣.mp3"
info        Failed to open file for reading
----------------------------------------------------------------------------------------------------
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:10864
load:0x40080400,len:6432
entry 0x400806b8
info        PSRAM found, inputBufferSize: 283615 bytes
info        buffers freed, free Heap: 312380 bytes
info        Reading file: "/良い一日私の友達.mp3"
info        Failed to open file for reading
----------------------------------------------------------------------------------------------------

**Comment by trullock** [comment]
Does `sd.h` support such file names?

**Comment by SyXavier** [comment]
Doesn't SdFat.h support UTF8 encoded file name?

**Comment by trullock** [comment]
Thats what I was asking and suggesting you test. FAT32 does support them, but I'm not sure (and tbh i doubt) Arduino does. Maybe I'm wrong...

**Comment by trullock** [comment]
If you look in the source, theres `SDFATFS_USED` which you need to define to support UTF-8 filenames

**Comment by SyXavier** [comment]
I have defined SDFATFS_USED, but it didn't work.

**Comment by schreibfaul1** [comment]
It is possible that SDFAT V2 does not support these 蜀绣 characters.
https://github.com/greiman/SdFat/issues/200

**Comment by SyXavier** [comment]
Hi, Wolle. I tested the SdFat library and it does support Unicode encoding. But using SdFat in the audio library does not open the file.
