### ISSUE TITLE
Audio clipping when connecting to new audio tracks

### ISSUE THREAD

**Issue by ggalisky** [schreibfaul1/ESP32-audioI2S#191]
Issue:

Running the sketch below causes audio clipping only after the first time a track has played. Each time a track ends and the next track plays there is audio clipping like this:

https://soundcloud.com/grayson-g-184358479/audio-issue

Hardware: 

Custom ESP32 dev board with a MAX98357AETE+T i2s class D amp and a small speaker. 

![image](https://user-images.githubusercontent.com/44689332/130540305-fbdb6c20-3a1f-4b22-909e-330515459c23.png)

Software:

#include "Audio.h"
#include "SD.h"
#include "FS.h"

// Digital I/O used
#define SD_CS          5
#define SPI_MOSI      23
#define SPI_MISO      19
#define SPI_SCK       18
#define I2S_DOUT      25
#define I2S_BCLK      27
#define I2S_LRC       26
bool endsong = false;
Audio audio;

void setup(){
    pinMode(SD_CS, OUTPUT);
    digitalWrite(SD_CS, HIGH);
    SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);
    Serial.begin(115200);
    SD.begin(SD_CS);
    audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
    audio.setVolume(21); // 0...21
    audio.connecttoFS(SD, "TEMP.mp3");
}

void loop(){
    audio.loop();
    if (endsong == true)
    {
   
     audio.connecttoFS(SD, "TEMP.mp3");
     endsong = false;
    }
}

// optional
void audio_info(const char *info){
    Serial.print("info        "); Serial.println(info);
}
void audio_id3data(const char *info){  //id3 metadata
    Serial.print("id3data     ");Serial.println(info);
}
void audio_eof_mp3(const char *info){  //end of file
    Serial.print("eof_mp3     ");Serial.println(info);
    endsong = true;
}
void audio_showstation(const char *info){
    Serial.print("station     ");Serial.println(info);
}
void audio_showstreaminfo(const char *info){
    Serial.print("streaminfo  ");Serial.println(info);
}
void audio_showstreamtitle(const char *info){
    Serial.print("streamtitle ");Serial.println(info);
}
void audio_bitrate(const char *info){
    Serial.print("bitrate     ");Serial.println(info);
}
void audio_commercial(const char *info){  //duration in sec
    Serial.print("commercial  ");Serial.println(info);
}
void audio_icyurl(const char *info){  //homepage
    Serial.print("icyurl      ");Serial.println(info);
}
void audio_lasthost(const char *info){  //stream URL played
    Serial.print("lasthost    ");Serial.println(info);
}
void audio_eof_speech(const char *info){
    Serial.print("eof_speech  ");Serial.println(info);
}

**Comment by schreibfaul1** [comment]
It will certainly not be due to the MAX9835.  At the end of the audio file, the audio buffer is completely emptied and everything that is in the I2S DMA buffer. Can you please insert the audio file here for testing or send me a link?
