### ISSUE TITLE
feature request : text to speech using FLITE without the need of internet connection

### ISSUE THREAD

**Issue by deladriere** [schreibfaul1/ESP32-audioI2S#198]
could it be possible to re-use this code : [https://github.com/alkhimey/esp32-flite](https://github.com/alkhimey/esp32-flite)
[https://www.youtube.com/watch?v=PcJnTQw0B4I](https://www.youtube.com/watch?v=PcJnTQw0B4I)
It would be really fun to have a local TTS with internet connection

**Comment by schreibfaul1** [comment]
Hello deladriere
I copied the code from flite and converted it to the Arduio version. The memory usage is too large and the speech output is moderate. The project is on my Github for use and further development

**Comment by deladriere** [comment]
Hi @schreibfaul1 
thanks a lot!
where can I find it?
did you get rid of the webserver (to save space) and just kept the text to speech?

**Comment by schreibfaul1** [comment]
The Arduino version of flite is in my Github Repo https://github.com/schreibfaul1/ESP32-flite-Arduino. If you are using PlatformIO there are no problems with compiling

**Comment by deladriere** [comment]
this link gives a 404 error ...

**Comment by schreibfaul1** [comment]
I had set the repository to 'archived'. Then I can only see it myself??? It's now public again

**Comment by deladriere** [comment]
Maybe I am not mapping the pins correctly ?

```
Arduino ESP32-audioI2S
// Digital I/O used
#define I2S_DOUT      25  // DIN connection
#define I2S_BCLK      27  // Bit clock
#define I2S_LRC       26  // Left Right Clock

Platformio ESP32-flite-Arduino
#define I2S_BCK_PIN 27
#define I2S_WS_PIN 26
#define I2S_DATA_PIN 25
```

**Comment by deladriere** [comment]
@schreibfaul1 do you also have this repeating click when done talking?

**Comment by FreeLANMan** [comment]
Maybe alternatively we can use Talkie:
https://www.youtube.com/watch?v=Q-VMNEvx4PE
https://github.com/bobh/ESP32Talkie

**Comment by schreibfaul1** [comment]
I had already experimented with this, but the audio quality is very poor.

**Comment by FreeLANMan** [comment]
So I think I'll use the SD Card and a solution with https://ttsmp3.com/
thanks
