### ISSUE TITLE
audio.setVolume

### ISSUE THREAD

**Issue by noevile** [schreibfaul1/ESP32-audioI2S#21]
If the radio works and change the volume, then the radio stops working. Need to restart "audio.connecttohost". Is it possible to change the volume without stopping the radio?

**Comment by schreibfaul1** [comment]
Hello noevile
Audio.loop () must be called cyclically otherwise the audiostream will stop.
Please test in the serial monitor:
````
void loop()
{
    if(Serial.available()>0){
        audio.setVolume(Serial.readString().toInt());
    }
    audio.loop();
}
````

**Comment by noevile** [comment]
Hello.
I'm sorry. My fault. Everything works great.
