### ISSUE TITLE
Stream .m3u not started 

### ISSUE THREAD

**Issue by Loucotolo** [schreibfaul1/ESP32-audioI2S#213]
Hello @schreibfaul1 

I'm trying to play the following url:

**http://servers.internet-radio.com/tools/playlistgenerator/?u=http://uplink.duplexfx.com:8002/listen.pls&t=.m3u**

but it does not work. I activated the log and I get the following:

> [1618140][V][ssl_client.cpp:302] stop_ssl_socket(): Cleaning SSL connection.
> [1618473][E][WiFiClient.cpp:267] connect(): socket error on fd 54, errno: 104, "Connection reset by peer"
> info        Request http://servers.internet-radio.com/tools/playlistgenerator/?u=http://uplink.duplexfx.com:8002/listen.pls&t=.m3u failed!

Could you solve the problem?

**Comment by schreibfaul1** [comment]
Hello Cellie, thanks for answering the question. The format is not m3u, it is pls.
