### ISSUE TITLE
Double promotions

### ISSUE THREAD

**Issue by FrankBoesing** [schreibfaul1/ESP32-audioI2S#219]
Hi, 

if you enable (-Wdouble-promotion) you'll see a number of warnings. As they have impact to a) speed (the ESP has no "double" capable FPU and calculates these things in software) and b) codesize you might want to fix these. Most of them are easy to fix by adding the "f" suffix to numbers.

Then, if've seen sqrt() .. etc. It's better to use i.e. sqrtf() to use the float- instead of the double versions of these functions (which, again are _much_ slower)

**Comment by FrankBoesing** [comment]
..And yes, the ESP Arduino core has this issue, too. :) I'll probably try do a PR there.

**Comment by schreibfaul1** [comment]
I had never switched on this compiler flag before, thanks for the hint

**Comment by FrankBoesing** [comment]
No problem. They were in less used functions and not that critical.

**Comment by FrankBoesing** [comment]
Hi,
sagmal, wo finde ich deine eMailadresse? Hab da einige Fragen.. geht besser per Mail...
