### ISSUE TITLE
Speakers don't work but earphone yes

### ISSUE THREAD

**Issue by dakota72** [schreibfaul1/ESP32-audioI2S#235]
Hi,
I connected the speakers and the earphone to my Esp32-a1s audio kit
I tried the example in ac101 library and works very well in both of case,
but the example ESP32_A1S.ino  works only with earphone, I don't know  why?
Can you help me?
dak.

**Comment by schreibfaul1** [comment]
On my board, GPIO 21 switches on the amplifier
````
// Amplifier enable
#define GPIO_PA_EN    21
````
````
  // Enable amplifier
  pinMode(GPIO_PA_EN, OUTPUT);
  digitalWrite(GPIO_PA_EN, HIGH);
````

**Comment by dakota72** [comment]
I resolved! thanks a lot!
