### ISSUE TITLE
[Question] - Is it possible to make ESP8266SAM compatible with ESP32-audioI2S ?

### ISSUE THREAD

**Issue by schmurtzm** [schreibfaul1/ESP32-audioI2S#248]
Hi, almost all is in the title.
[ESP8266SAM](https://github.com/earlephilhower/ESP8266SAM) is a library natively compatible with [ESP8266Audio](https://github.com/earlephilhower/ESP8266Audio/) library.
Sam voice has a bad pronunciation quality compared to Google TTS and it's English only ... But it can work offline !

The idea is to use an ESP32 for home automation notifications. I was thinking that if my internet connection is down it could be useful to keep possible to send TTS notifications without Google TTS.

I took an eye in this ESP8266SAM library and the audio stream seems to be generated around [this line](https://github.com/earlephilhower/ESP8266SAM/blob/master/src/ESP8266SAM.cpp#L83).

Seems possible to port it to  ESP32-audioI2S, isn't it ?

------------------------------
Edit: alternative TTS libraries found thanks to [this blog](https://www.pschatzmann.ch/home/2021/06/23/text-to-speach-in-arduino-conclusions/) : 
https://github.com/pschatzmann/arduino-SAM , seems a little similar to ESP8266SAM, well documented, [sample here](https://www.pschatzmann.ch/home/2021/06/22/text-to-speach-in-arduino/).
https://github.com/pschatzmann/TTS  , not based on sam voice, [the result sample](https://www.pschatzmann.ch/home/2021/06/22/text-to-speach-in-arduino-using-tts/) is very robotic but fun 😋 
https://github.com/pschatzmann/arduino-flite  ([flite](https://github.com/festvox/flite) use more memory than SAM but better result , [sample here](https://www.pschatzmann.ch/home/2021/06/23/text-to-speach-in-arduino-using-flite/) or [here](http://festvox.org/voicedemos.html))

**Comment by schreibfaul1** [comment]
The voice quality is not convincing. See beginning of https://www.youtube.com/watch?v=4ig14PAZ2Dw. There is a project for flite in my repository https://github.com/schreibfaul1/ESP32-flite-Arduino The quality is also bad.

**Comment by schmurtzm** [comment]
Yes it's not good... but it work offline which can be useful in some case.
Awesome, you have already tested it ! You make a lot of things ;) 
Why your flite project is not based on ESP32-audioI2S ? Flite doesn't generate a classical wav ?
