### ISSUE TITLE
Connection is not closed

### ISSUE THREAD

**Issue by biologist79** [schreibfaul1/ESP32-audioI2S#27]
I integrated your lib into a port of the Tonuino-project (code not yet online) using ESP32. However, I recognized the first webstream is no problem, but coming up with a new one (after calling `audio.stopSong();` let to the problem, that no further webclient-connection is available (I'm running MQTT-connections in parallel). However, I checked your code and discovered
`clientsecure.stop(); clientsecure.flush(); // release memory`
in Audio.cpp:103. Is there a reason why you don't reset unsecured connectons as well? Anyway, I added 
`client.stop(); client.flush(); // release memory`
and now it works for me.

**Comment by schreibfaul1** [comment]
Hello biologist79,
Client stop / flush will probably only have an effect if other connections are also set up. Thanks for the hint, I have client.stop (); Client.flusch () added
