### ISSUE TITLE
SPIFFs with SDFat impossible

### ISSUE THREAD

**Issue by nodoubtman** [schreibfaul1/ESP32-audioI2S#271]
Hello... I would like to use spiffs with SDFat System, but i cannot... 
is it possible to do a work around?

Thanks.
Marc.

**Comment by schreibfaul1** [comment]
That does not work. SDFat comes with its own file system. This is not compatible with that of Espressif. SPIFFS, SD, SD_MMC are therefore not possible.

**Comment by nodoubtman** [comment]
> That does not work. SDFat comes with its own file system. This is not compatible with that of Espressif. SPIFFS, SD, SD_MMC are therefore not possible.

Thanks.
Can i get another sd card which is not sdhc that can work ?
Thanks.
Marc.

**Comment by schreibfaul1** [comment]
I don't quite know what the question means. Regarding SDFat I have no idea.
A second instance can be created with the ESP32 libraries (SD1, SD2, ...) I think this must be enabled in the sdkconfig, the default is one instance.

**Comment by nodoubtman** [comment]
ok
