### ISSUE TITLE
Playlist M3U

### ISSUE THREAD

**Issue by dmb-220** [schreibfaul1/ESP32-audioI2S#273]
how to next radio station for playslist radio.pervii.com/top_radio_pop.m3u. play first playlist radio statio URL

**Comment by schreibfaul1** [comment]
Many radio stations publish their StreamURLs as m3u. The library searches for the first valid URL and connects to it, nothing more is done.

http://radio.pervii.com/top_radio_pop.m3u is a list of different radio stations. An extension for switching between the channels must be programmed by yourself.
