### ISSUE TITLE
How to change web radio stations

### ISSUE THREAD

**Issue by marchingband** [schreibfaul1/ESP32-audioI2S#277]
Hello
I'd like to connect to a URL, then in response to a button press, connect to a different URL ... basically change the station on demand.
What is the correct way to do this? I am getting a lot of crashes, with using audio.stopSong() and then audio.connecttohost(URL).
Is it possible for this transition to be seamless? Ideally I'd like to keep playing the first station while the second one connects and buffers, and then quickly switch over.
thank you! loving this library!

**Comment by nodoubtman** [comment]
// SLEEP RADIO
bool hostConnected =  audio.connecttohost("http://149.56.234.138:8169/stream");

Serial.println(hostConnected ? F("HOST CONNECTED") : F("CANNOT CONNECT TO HOST!") );


in the loop

void loop(){
 audio.loop();
}

**Comment by marchingband** [comment]
thanks @nodoubtman I found my crash elsewhere.
Has anyone tried using an AsyncClient, or something like that, to buffer http streams before switching?
