### ISSUE TITLE
ESP32-S2 compile error :-(

### ISSUE THREAD

**Issue by pbenaim** [schreibfaul1/ESP32-audioI2S#292]
I have many ESP32-S2 compile error :-(

Any idea to solve it ?

Thanks

**Comment by Quaestuosa** [comment]
Hello,
maybe you have a similar problem as I had. This library requires a ESP32 module that has two processor cores.
Please see https://github.com/schreibfaul1/ESP32-audioI2S/issues/290
Cheers
