### ISSUE TITLE
Just a question:

### ISSUE THREAD

**Issue by nodoubtman** [schreibfaul1/ESP32-audioI2S#295]
Hey, just a question:

Does that makes sense? 👍 

` if (audio.isRunning())
    audio.loop();
`

THanks for letting me know:)
Marc.

**Comment by nodoubtman** [comment]
ok then!

**Comment by schreibfaul1** [comment]
Hello Marc,
if the audio library has nothing to do, the loop is immediately jumped back. I don't think querying isRunning in addition will bring any improvement.

best regards
Wolle
