### ISSUE TITLE
MP3 decode error -2

### ISSUE THREAD

**Issue by ZnakZorro** [schreibfaul1/ESP32-audioI2S#30]
What means "MP3 decode error -2"?

**Comment by schreibfaul1** [comment]
"MP3 decode error -2"  means not enough data in bit reservoir from previous frames. That can happen if decoding is started in the middle of the stream.

**Comment by ZnakZorro** [comment]
Thank you for the advice!
I have corrected the code.
There is no error -2.
But I still can't hear anything from the speakers.
Either noise or silence.
Here is my test code:
https://github.com/ZnakZorro/ESP32-audioI2S/blob/master/start_esp32_radio.ino

What is wrong?

**Comment by ZnakZorro** [comment]
Sorry, my pinout error.
Now it is working, i can hear the sound.
Thanks for the great library

**Comment by schreibfaul1** [comment]
Glad to hear that
