### ISSUE TITLE
support esp32s3 dlna render

### ISSUE THREAD

**Issue by modi12jin** [schreibfaul1/ESP32-audioI2S#308]
@schreibfaul1 Hi! Are you planning to support the DLNA media renderer?(Since the S3 doesn't have classic bluetooth, I thought of playing the music from the phone via the DLNA media renderer)

**Comment by schreibfaul1** [comment]
I can't tell yet. The DLNA media protocol would be possible and I believe that is implemented in the Espressif Audio Development Framework.

**Comment by modi12jin** [comment]
@schreibfaul1 I don't know if you've seen this

![Screenshot_20220521_094529_com android chrome](https://user-images.githubusercontent.com/40233017/169629809-890f9532-9830-4708-9031-d8a1117e1472.jpg)

https://github.com/yellobyte/SoapESP32

**Comment by schreibfaul1** [comment]
DLNA is a good thing. Unfortunately, the ESP32 DLNA renderer cannot find my media server in the home network. I can see the multicast and also the replies to it, but the media server is ignored. I'll figure out why later, thanks for sharing.
Soap32 finds the media server immediately and also displays the directories.

**Comment by modi12jin** [comment]
@schreibfaul1  Someone ported the ADF framework to the Arduino platform

【我成功将ESP-ADF移植到了Arduino上，并封装成ArduinoADFSimplify库，ESP32音频开发不再有门槛-哔哩哔哩】 https://b23.tv/h1f7luY

**Comment by schreibfaul1** [comment]
Hello [modi12jin](https://github.com/modi12jin),
DLNA is complex and I can't integrate the function into the library. You will find a DLNA complete project in the 'Examples' folder. I created this in a hurry, I'm sure there are still many errors in it. But it works for me.
