### ISSUE TITLE
Error Compiling 

### ISSUE THREAD

**Issue by rihani** [schreibfaul1/ESP32-audioI2S#31]
Could you please help,  i am unable to compile, here is my error

Archiving built core (caching) in: /tmp/arduino_cache_561838/core/core_esp32_esp32_esp32_PSRAM_disabled,PartitionScheme_default,CPUFreq_240,FlashMode_qio,FlashFreq_80,FlashSize_4M,UploadSpeed_921600,DebugLevel_none_c553e1c789170525c91403689da85e69.a
Multiple libraries were found for "SD.h"
 Used: /home/ossama/snap/arduino-mhall119/5/.arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/SD
 Not used: /snap/arduino-mhall119/5/libraries/SD
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xbc): undefined reference to `MP3FindSyncWord(unsigned char*, int)'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xc0): undefined reference to `AACFindSyncWord(unsigned char*, int)'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xc4): undefined reference to `MP3Decode(unsigned char*, int*, short*, int)'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xc8): undefined reference to `AACDecode(unsigned char*, int*, short*)'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xcc): undefined reference to `MP3GetChannels()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xd0): undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xd8): undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xdc): undefined reference to `MP3GetBitrate()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xe0): undefined reference to `MP3GetOutputSamps()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xe4): undefined reference to `AACGetChannels()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xe8): undefined reference to `AACGetSampRate()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xec): undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xf0): undefined reference to `AACGetBitrate()'
sketch/Audio.cpp.o:(.literal._ZN5Audio9sendBytesEPhj+0xf4): undefined reference to `AACGetOutputSamps()'
sketch/Audio.cpp.o: In function `Audio::sendBytes(unsigned char*, unsigned int)':
sketch/Audio.cpp:1706: undefined reference to `MP3FindSyncWord(unsigned char*, int)'
sketch/Audio.cpp:1706: undefined reference to `AACFindSyncWord(unsigned char*, int)'
sketch/Audio.cpp:1706: undefined reference to `MP3Decode(unsigned char*, int*, short*, int)'
sketch/Audio.cpp:1706: undefined reference to `AACDecode(unsigned char*, int*, short*)'
sketch/Audio.cpp:1706: undefined reference to `MP3GetChannels()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetChannels()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetChannels()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetChannels()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp.o:sketch/Audio.cpp:1706: more undefined references to `MP3GetSampRate()' follow
sketch/Audio.cpp.o: In function `Audio::sendBytes(unsigned char*, unsigned int)':
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetOutputSamps()'
sketch/Audio.cpp:1706: undefined reference to `AACGetChannels()'
sketch/Audio.cpp:1706: undefined reference to `AACGetChannels()'
sketch/Audio.cpp:1706: undefined reference to `AACGetChannels()'
sketch/Audio.cpp:1706: undefined reference to `AACGetChannels()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp.o:sketch/Audio.cpp:1706: more undefined references to `AACGetSampRate()' follow
sketch/Audio.cpp.o: In function `Audio::sendBytes(unsigned char*, unsigned int)':
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetOutputSamps()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetSampRate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitrate()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `MP3GetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp:1706: undefined reference to `AACGetBitsPerSample()'
sketch/Audio.cpp.o:sketch/Audio.cpp:1706: more undefined references to `AACGetBitsPerSample()' follow
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by Quas7** [comment]
I run into a similiar "undefined reference to" compilation error during linking. This happens with platform.io as well as Arduino IDE.
I use 1.22.0-97-gc752ad5-5.2.0 xtensa-esp32-elf-gcc.

Will check now, if this is a path lenght issue.
