### ISSUE TITLE
ogg doesn't seems to work

### ISSUE THREAD

**Issue by podaen** [schreibfaul1/ESP32-audioI2S#312]
> Auto Next
> http://streaming.domainepublic.net:8000/radioairlibre.ogg
> 
> write eeprom UrlSelector: 155
> info        buffers freed, free Heap: 84008 bytes
> info        Connect to new host: "http://streaming.domainepublic.net:8000/radioairlibre.ogg"
> info        Connect to "streaming.domainepublic.net" on port 8000, extension "/radioairlibre.ogg"
> info        Connection has been established in 66 ms, free Heap: 81428 bytes
> info        HTTP/1.0 200 OK
> info        server: Icecast 2.4.4
> info        date: Sat, 21 May 2022 13:06:26 GMT
> info        ContentType application/ogg found
> info        access-control-allow-origin: *
> info        ice-audio-info: channels=2;quality=0.5;samplerate=48000
> info        icy-name: Radio Air Libre
> info        Switch to DATA, metaint is 0
> info        stream ready
> info        buffer filled in 295 ms
> [601123][I][Audio.cpp:1973] read_OGG_Header(): ogg/flac support only
> 
> Auto Next
> https://streaming.domainepublic.net/radiopanik.ogg
> 
> write eeprom UrlSelector: 156
> info        buffers freed, free Heap: 84016 bytes
> info        Connect to new host: "https://streaming.domainepublic.net/radiopanik.ogg"
> info        Connect to "streaming.domainepublic.net" on port 443, extension "/radiopanik.ogg"
> [640271][D][ssl_client.cpp:174] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
> [640661][E][WiFiClient.cpp:336] setOption(): fail on fd -1, errno: 9, "Bad file number"
> info        SSL has been established in 424 ms, free Heap: 39300 bytes
> info        HTTP/1.1 200 OK
> info        date: Sat, 21 May 2022 13:07:06 GMT
> info        server: Icecast 2.4.4
> info        strict-transport-security: max-age=15768000
> info        x-content-type-options: nosniff
> info        x-frame-options: SAMEORIGIN
> info        ContentType application/ogg found
> info        access-control-allow-origin: *
> info        ice-audio-info: channels=2;quality=0.3;samplerate=48000
> info        icy-country-code: be
> info        icy-country-subdivision-code: be-bru
> info        icy-geo-lat-long: 50.85086,4.37424
> info        icy-index-metadata: 1
> info        icy-logo: https://www.radiopanik.org/static/img/logo-panik-500-invert.png
> info        icy-main-stream-url: https://streaming.domainepublic.net/radiopanik.ogg
> info        icy-name: Radio Panik
> info        Switch to DATA, metaint is 0
> info        stream ready
> info        buffer filled in 159 ms
> [641373][I][Audio.cpp:1973] read_OGG_Header(): ogg/flac support only
> 
> Auto Next
> http://streaming.domainepublic.net:8000/radiosud.ogg
> 
> write eeprom UrlSelector: 157
> info        buffers freed, free Heap: 84224 bytes
> info        Connect to new host: "http://streaming.domainepublic.net:8000/radiosud.ogg"
> info        Connect to "streaming.domainepublic.net" on port 8000, extension "/radiosud.ogg"
> info        Connection has been established in 25 ms, free Heap: 82020 bytes
> info        HTTP/1.0 200 OK
> info        server: Icecast 2.4.4
> info        date: Sat, 21 May 2022 13:07:46 GMT
> info        ContentType application/ogg found
> info        access-control-allow-origin: *
> info        ice-audio-info: ice-samplerate=44100;ice-bitrate=320;ice-channels=2
> info        icy-name: Radio Sud
> info        Switch to DATA, metaint is 0
> info        stream ready
> info        buffer filled in 13 ms
> [680707][I][Audio.cpp:1973] read_OGG_Header(): ogg/flac support only

**Comment by schreibfaul1** [comment]
An ogg decoder is not installed. But ogg can contain other file formats, such as flac. So the ogg header is unwrapped, but the procedure aborts if it's not a flac.
