### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by podaen** [schreibfaul1/ESP32-audioI2S#313]
Congratz! I have tested more than 200 webstreams and most links work. Even if it didn't work with one codec I could made it work with an other.

**Comment by podaen** [comment]
Note #311

**Comment by schreibfaul1** [comment]
Thanks!
We have an ESP32 here. The performance of a PC is not reached. Many stations offer streams with different bandwidths. With a reduced bandwidth, dropouts can often be avoided. Replacing https:// with http:// often helps

best regards
Wolle

**Comment by podaen** [comment]
I know he resources are limited. The most importend link did work. So I am glad. I will try to replace the https stream wit http.

Regards
Davy
