### ISSUE TITLE
Mute to zero.

### ISSUE THREAD

**Issue by podaen** [schreibfaul1/ESP32-audioI2S#319]
I have tested it this weekend and evryting works great, just a small detail about the volume controle. When I set the volume to 0, there is still knacking sound coming out and sure when there is music playing. It's like mute isn't mute be just set to zero. Maybe by setting at as a nullptr istead of zero...

**Comment by schreibfaul1** [comment]
that looks correct, in playSample() before i2s_write(...)
````c++
    #include assert.h
    if(m_vol == 0){
        assert(s32 == 0);
    }
````
there is only NULL on the I2S
I suspect the noise comes from the operating voltage

**Comment by podaen** [comment]
Hmmm, I pulled the decoder out and now I have absolute silence. Sp it is not coming from my amp or the transformer. Maybe I need to use a mute pin on the decoder if there is...

**Comment by podaen** [comment]
XSMT seems to be such a pin.

**Comment by schreibfaul1** [comment]
I only connect SCK to GND, XSMT is open

**Comment by podaen** [comment]
Wait, what! I have a black PCM5102a

I have...

VCC ->3V
3.3V -> 3.3V
GND -> GND
FLT 
DMP
SCL
BLK ->26
DIN -> 27
LCK -> 25
FMT -> GND
XMT -> 3.3V

![2022-05-30_092054](https://user-images.githubusercontent.com/63886347/170938704-212ac2c1-2c80-43ca-9081-4fb7adcf0258.jpg)

According to my datasheet xmt neets to be high for unmute...

**Comment by schreibfaul1** [comment]
I have this DAC, SCK could be the same as SCL
![image](https://user-images.githubusercontent.com/26044260/170940341-4d915f24-c6a0-4baf-b033-30eaee6c93cd.png)

**Comment by podaen** [comment]
I will connected to ground. having that board too, stored one of my boxes. For now I will try to do this one work, first try to mute it... if that goos well, than I will do a ESP sleep over night. And solder things up like I sad.

**Comment by podaen** [comment]
I have done what you sad and it is much bether now, also the soldering helpt a lot. The mut pin wasn't an improvement like I was especting. I will close this issue now.
