### ISSUE TITLE
mary TTS not working

### ISSUE THREAD

**Issue by deladriere** [schreibfaul1/ESP32-audioI2S#324]
I can run  audio.connecttospeech
but audio.connecttomarytts doesn't work

**Comment by schreibfaul1** [comment]
Hello deladriere,
Mary also needs the voice, please have a look at the routine, I have listed the possible voices there.

audio.connecttomarytts("Dies ist ein Test. Schön zu hören, dass es funktioniert.", "de", "bits1");

Best regards from Berlin
Wolle

**Comment by deladriere** [comment]
Working fine now 
Thanks!
Any chance to also use audio effects? This would be great!
