### ISSUE TITLE
How to compile this project?

### ISSUE THREAD

**Issue by alexsandro-xpt** [schreibfaul1/ESP32-audioI2S#33]
Where those files?

https://github.com/schreibfaul1/ESP32-audioI2S/blob/3b8339463ef6e81701393963aa0d67ffa20b6311/src/Audio.cpp#L17-L18

What the steps to build this project?

**Comment by schreibfaul1** [comment]
In Arduino IDE You can install a library this way: https://www.arduino.cc/en/Guide/Libraries
Download this repository as zip and use the Library Manager
