### ISSUE TITLE
Changing volume does not change sound output

### ISSUE THREAD

**Issue by ggalisky** [schreibfaul1/ESP32-audioI2S#337]
No matter what value I pass through I cannot get the gain to increase or decrease

**Comment by geareye** [comment]
I'm trying to find my way around the code, I've not used ESP32 before, but I'm familiar with ATMEL, TI and STMicro so it should be easy to follow, but where in the fw are you handling this? Maybe this is a good point for me to dive in from...Also do you guys use pull requests?
