### ISSUE TITLE
Trouble with connection timeouts

### ISSUE THREAD

**Issue by spam-this** [schreibfaul1/ESP32-audioI2S#342]
Thank you for publishing this excellent software.  I was just trying the i2Saudio example and had to add
 
   audio.setConnectionTimeout(3000, 4000);

to make it work.  The default timeout of 250 ms looks very small to me.  I also see this in Audio.cpp:

    if(ESP_ARDUINO_VERSION_MAJOR == 2 && ESP_ARDUINO_VERSION_MINOR == 0 && ESP_ARDUINO_VERSION_PATCH == 3){
        m_timeout_ms_ssl = UINT16_MAX;  // bug in v2.0.3 if hostwoext is a IPaddr not a name                                
        m_timeout_ms = UINT16_MAX;  // [WiFiClient.cpp:253] connect(): select returned due to timeout 250 ms for fd 48      
    }

Perhaps you want to apply for for versions >= 2.0.3?  I am using 2.0.4.

Cheers and thanks again.

**Comment by schreibfaul1** [comment]
Thanks for the hint. It worked like this up to version 2.0.2. The connection time hasn't increased, but obviously something about the timeout rating. I will accept your suggestion.
