### ISSUE TITLE
After piggyback a PSRAM glitches continues

### ISSUE THREAD

**Issue by renatoianhez** [schreibfaul1/ESP32-audioI2S#345]
Hi!
I make [this](https://blog.pagefault-limited.co.uk/lolin32-lite-esp32-8mb-psram-upgrade-mod) in my Lolin32 Lite and I got a "PSRAM found" (Hurrah!). 
![image](https://user-images.githubusercontent.com/34423009/180107769-5f97599d-6a3e-4697-ae4a-136fcc9b9d9e.png)
In a PSRAM test I got:
![image](https://user-images.githubusercontent.com/34423009/180107906-e8af0024-f8b3-41e5-beb5-4de09d8f10f6.png)

But the dropouts continues, although they have decreased a little bit. In order for it to work, I had to change the upload to the settings below:
![image](https://user-images.githubusercontent.com/34423009/180107611-c35ad149-1f6e-40a1-8e94-49a51cede188.png)

Did I do something wrong?

**Comment by schreibfaul1** [comment]
On the ESP32, the PSRAM is connected via SPI, that's one reason why PSRAM is slower than SRAM. The ESP32-S3 has a quad and sometimes an octo SPI. Then the access times to the PSRAM are significantly faster and much better suited for audio applications.
