### ISSUE TITLE
WAV links doesn't work 

### ISSUE THREAD

**Issue by sergi-reus-code** [schreibfaul1/ESP32-audioI2S#360]
I've tested this...

audio.connecttoFS(SD, "/320k_test.mp3");  ---> OK
audio.connecttoFS(SD, "/Pink-Panther.wav");   ---> DON'T PLAY      

audio.connecttohost("http://www.wdr.de/wdrlive/media/einslive.m3u");  ---> OK

audio.connecttohost("https://github.com/schreibfaul1/ESP32-audioI2S/raw/master/additional_info/Testfiles/Pink-Panther.wav");  ---> DON'T PLAY

audio.connecttohost("https://github.com/schreibfaul1/ESP32-audioI2S/raw/master/additional_info/Testfiles/320k_test.mp3");  ---> OK

audio.connecttospeech("Wenn die Hunde schlafen, kann der Wolf gut Schafe stehlen.", "de");  ---> OK

Please, can someone help me?¿

Thanks

**Comment by podaen** [comment]
What error do you get in the exception decoder?

**Comment by schreibfaul1** [comment]
Your system is probably running without PSRAM. Please look in the audio.h (line 467) and set the value for m_frameSizeWav from the current 1024*8 to a maximum of 1600. Does it work then?

**Comment by sergi-reus-code** [comment]
GREAT.......!!!!

WORKS FINE!!!!

Thanks.....,

**Comment by schreibfaul1** [comment]
thanks, I will adjust the value automatically if no PSRAM is available.
