### ISSUE TITLE
in funtion processWebStream() please add for speech 

### ISSUE THREAD

**Issue by pavankarney** [schreibfaul1/ESP32-audioI2S#366]
if(f_tmr_1s && InBuff.bufferFilled() < maxFrameSize && !availableBytes){
if(m_f_tts){stopSong();return;}
else { 
cnt_slow ++;
 if(cnt_slow > 50){cnt_slow = 0;  f_tmr_1s = false; AUDIO_INFO("slow stream, dropouts are possible");}
		}
    }

**Comment by schreibfaul1** [comment]
sorry, wrong streamtype
It should work now, thanks for the tip

**Comment by pavankarney** [comment]
perfect now, thank you..
