### ISSUE TITLE
Clicking noise when pausing

### ISSUE THREAD

**Issue by mhier** [schreibfaul1/ESP32-audioI2S#37]
When pausing audio, I get some clicking noise for a short period of time. This can be avoided by flushing the buffer just like it is done in stopSong(). Hence I suggest to change pauseResume() like this:

```
bool Audio::pauseResume()
{
    bool retVal = false;
    if(m_f_localfile || m_f_webstream)
    {
        m_f_running = !m_f_running;
        retVal = true;
        if(!m_f_running) {
            i2s_zero_dma_buffer((i2s_port_t)m_i2s_num);
            memset(m_outBuff, 0, sizeof(m_outBuff));               //Clear OutputBuffer
        }
    }
    return retVal;
}
```

Btw: I also found it useful to have functions like pause() and resume() separately...

**Comment by schreibfaul1** [comment]
Thanks for the tip, I have incorporated the change
