### ISSUE TITLE
Using external RAM as a buffer?

### ISSUE THREAD

**Issue by michelep** [schreibfaul1/ESP32-audioI2S#39]
Thanks for your work! It's really awesome. However, i often got a buffer underrun and i'm thinking if should be possible to use an external RAM via SPI like 23LC1024 for buffering

**Comment by schreibfaul1** [comment]
Hello michelep,
For me this problem does not occur, I suspect that the buffer is not filled quickly enough, maybe the CPU frequency is not 240MHz?

**Comment by michelep** [comment]
Thanks for your reply. I've solved moving audio tasks to CPU0, while mantaining all other tasks to the other core CPU1 :-)

**Comment by michelep** [comment]
If you want, take a look to ESP32_WebRadio project on my repo ;-)

**Comment by schreibfaul1** [comment]
Yes, gladly, a look at the web radio would be good, but an RPI display 320x480px is required.

**Comment by michelep** [comment]
I prefer an old looking Nokia 5110 display with 4 capacitive buttons :)

8 Mag 2020 18:43:55 Wolle <notifications@github.com>:

**Comment by reaper7** [comment]
> 
> 
> Thanks for your reply. I've solved moving audio tasks to CPU0, while mantaining all other tasks to the other core CPU1 :-)

@michelep - tnx for the tip! 
my m5stickc + PCM1502A very often interrupted playback from network stream (stations from this lib example), when I moved audio.loop to cpu0 the stream plays without clipping :)

**Comment by schreibfaul1** [comment]
Perfect, the distribution of the tasks on both cores can be a good solution for some projects.

**Comment by schreibfaul1** [comment]
Didn't understand a word, but great video :-)
https://www.youtube.com/watch?v=sVKdvpsTuFA

**Comment by michelep** [comment]
Thanks, my english is not so good and i'm a bit ashamed to make videos in that language
