### ISSUE TITLE
Does this lib surpport flac format?

### ISSUE THREAD

**Issue by justdomyself** [schreibfaul1/ESP32-audioI2S#394]
I use it play mp3 is ok, but i use it play flac format music, there is no sound。

I find  source files in the examples about flac, so I think maybe it support  flac format musics。

**Comment by schreibfaul1** [comment]
This works as long as flac is not embedded in an ogg stream. PSRAM is required.
Example: audio.connecttohost("https://raw.githubusercontent.com/schreibfaul1/ESP32-audioI2S/master/additional_info/Testfiles/Santiano-Wellerman.flac");

**Comment by justdomyself** [comment]
> 
I mean I play the music on the sd card, the mp3 format is ok ?but  flac can't work

**Comment by justdomyself** [comment]
> 
i use esp32 wrover module, it has psram。 how can i use it with your code .I do not understand " not embedded in an ogg stream. ", what does it mean?

**Comment by schreibfaul1** [comment]
ogg is a wrapper to make FLAG capable of streaming and is not currently supported

**Comment by schreibfaul1** [comment]
Only 'native' FLAC works. For example, files from the SD card (or from the webserver)

````
audio.connecttohost("https://github.com/schreibfaul1/ESP32-audioI2S/raw/master/additional_info/Testfiles/Santiano-Wellerman.flac");
````
