### ISSUE TITLE
I compile esp32 arduino project by vs code(use platformio plugin), connecttohost can not play music ?

### ISSUE THREAD

**Issue by justdomyself** [schreibfaul1/ESP32-audioI2S#395]
1 、I compile esp32 arduino project by vs code(use platformio plugin), connecttohost can not play music on the internet，but    use audio.connecttoFS(SD_MMC, "1.mp3") play music on sd card is ok。

2、If I use arduino ide compile the same project, all is ok，there is no any problem。

**Comment by justdomyself** [comment]
can your this project with the config play flac music ok?

**Comment by justdomyself** [comment]
can your this project with the config play flac music ok?

**Comment by schreibfaul1** [comment]
The FLAC standard is diverse. There are limitations due to the limited resources of the ESP:
bits per sample <= 16,
Number of channels <= 2
Block size <= 8KB
