### ISSUE TITLE
What does setChannels mean?

### ISSUE THREAD

**Issue by murarduino** [schreibfaul1/ESP32-audioI2S#397]
Notice the setChannels method defined in Audio.h. But I don't know how to use it. Is it possible to mix the sound of several channels?
In addition, it is also hoped that AudioI2S can support mixing output, so that it can be more flexible to produce complex music. 
Thanks .

**Comment by schreibfaul1** [comment]
setChannels() is a private function and is used by the decoders. A mix of several audio sources is not possible
