### ISSUE TITLE
MP3 decode error -3

### ISSUE THREAD

**Issue by olup** [schreibfaul1/ESP32-audioI2S#4]
Hi
Kudos for the great work here. I don't understand everything when it comes to mp3 decoding, but i am running into a dead end with a file at this address : 

http://media.radiofrance-podcast.net/podcast09/10059-31.03.2019-ITEMA_22023210-0.mp3

It seems the decoder has trouble reading it, and that end up messing the bitrate detection, giving the ERR_FREE_BITRATE_SYNC.
It's looking for a proper frame, skipping many of them, then calculates a zero bitrate, starts looking again, find a frame, and then crashes :
`
Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception) 
Debug exception reason: /Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/tasks.c:2331 (pcTaskGetTaskName)- assert failed!
abort() was called at PC 0x4008ff96 on core 0
`

Any idea what cause such error in this particular file (and of every files of this radio) ? Could I default the bitrate to 128 if it cannot be calculated ?

Cheers !

**Comment by schreibfaul1** [comment]
Hello olup,
http://media.radiofrance-podcast.net/podcast09/10059-31.03.2019-ITEMA_22023210-0.mp3 is not a usual mp3 radio stream, it is a podcast. Podcasts may have an ID3-Tag at the beginning. That's why the decoder can not found the next syncword (in this case the ID3 info is ~150k long). As a first workaround, the ID3-Tag is skipped.

**Comment by olup** [comment]
This is extreemely interesting, I had no idea of the inner works of podcasts, need to go back digging. So, if I understand you correctly, you think the problem could be solved by trying to skip the ID3 tag of the begining, wich involve I guess first geting the tag size and then offsetting the read from there ? I have no idea on how to do that but i'll start looking. Cheers.

**Comment by olup** [comment]
Ha ! you actually just commited those changes ! thanks a lot, i'll give it a spin in the morning !

**Comment by olup** [comment]
A thousands thanks for this very quick update of the library, this is now working flawlessly. Thank you !
