### ISSUE TITLE
https streams, not correct playback. Solution to the problem.

### ISSUE THREAD

**Issue by rv9c** [schreibfaul1/ESP32-audioI2S#40]
Thanks for the project!
Found a small error when playing streams with encryption in particular https, some streams sent the controller to reboot. Others did not play correctly.

Audio.cpp 
[https://github.com/schreibfaul1/ESP32-audioI2S/blob/master/src/Audio.cpp](url)

Actual for nttp flows
line 924  `int b = client.read ();`
completely forgot about https)

I propose to replace it with:
```
int b;
if (m_f_ssl == false)
{
    b = client.read ();
}
if (m_f_ssl == true)
{
     b = clientsecure.read ();
}
```

And also exclude the condition 
line 823
```
 if ( bytesAddedToBuffer == 0 )
            {
                if ( m_f_stream )
                {
                    m_f_stream = false;
                    i2s_zero_dma_buffer((i2s_port_t)m_i2s_num);
                    if(audio_info) audio_info("stream lost");
                }
            }
```

Sorry for my English)

**Comment by schreibfaul1** [comment]
Very good, thank you!
