### ISSUE TITLE
Extending connecttoSD to connecttoFS

### ISSUE THREAD

**Issue by vvs551** [schreibfaul1/ESP32-audioI2S#41]
Could you extend connecttoSD to the more universal method for using SPIFFS and SD in the same time?

bool Audio::connecttoFS(fs::FS &fs, String sdfile){
...
    //fs::FS &fs=SD;

**Comment by schreibfaul1** [comment]
I added the function connecttoFS(...)

**Comment by jwktje** [comment]
Does this mean we could use audio files in the Flash of the ESP?

**Comment by schreibfaul1** [comment]
Yes, it works, load an mp3 file in the SPIFF (eg with the Arduino IDE) and then play it: audio.connecttoFS (SPIFFS, "test.mp3");

**Comment by jvet88** [comment]
This throws me an error: 'SPIFFS' was not declared in this scope

**Comment by schreibfaul1** [comment]
At the beginning ````#include "SPIFFS.h````  
in setup() ````SPIFFS.begin();````
and later call e.g.   ````audio.connecttoFS(SPIFFS, "wobble.mp3");````
