### ISSUE TITLE
New asx format

### ISSUE THREAD

**Issue by tv4you2016** [schreibfaul1/ESP32-audioI2S#413]
hello @schreibfaul1 

With this link **http://somafm.com/wma128/missioncontrol.asx** the playback format is Content-Type: **audio/x-ms-asx**

This just add this in

> parseContentType
>     else if(!strcmp(ct, "video/x-ms-asf")) ct_val = CT_ASX;
>     else if(!strcmp(ct, "audio/x-ms-asx")) ct_val = CT_ASX;
> 

tested by me and functional

**Comment by schreibfaul1** [comment]
Thanks for your contribution, I added the Content-Type "audio/x-ms-asx" . The stream "NASA Mission Control" works now. :-)
