### ISSUE TITLE
ESP32 Webradio Error

### ISSUE THREAD

**Issue by sureshmagnolia** [schreibfaul1/ESP32-audioI2S#414]
Hi 
I am trying to make a web radio based on your code
getting this error on on compiliation, i am novice on coding, couldnt figure the problem myself. pls help

Error: 
src/Audio.h:380:55: error: expected ';' before ',' token
         if(result > SIZE_MAX) {log_e("range overflow"), result = 0;}; // overflow

**Comment by schreibfaul1** [comment]
Thanks for the hint! That's a typo, got semicolon mixed up with comma.
It's amazing that my compiler doesn't complain.

**Comment by sureshmagnolia** [comment]
Ok thanks a lot, replaced comma with semi colon, now that error gone, but another array of errors popped up
