### ISSUE TITLE
Audible click when using internal DAC

### ISSUE THREAD

**Issue by dmarc1234** [schreibfaul1/ESP32-audioI2S#427]
I am using the internal DAC setting with this library and it works okay for MP3 playback.

The issue is that I get a loud audible click at the beginning of playback and at the end which is caused by the DAC output going to half rail at the start and back to ground at the end.

I have tried re-biasing the signal to half rail externally but the click is still audible, so is there a way that the DAC can be set at half rail on initialisation and left there after playback?

**Comment by schreibfaul1** [comment]
I2S runs constantly and does not cause any problems with an external DAC. 
You can turn off I2S after the 'end of file' in the processLocalFile() routine with ``I2Sstop(m_i2s_num);``
And switch on with ``I2Sstart(m_i2s_num);`` after if(m_f_firstCall)

**Comment by dmarc1234** [comment]
@schreibfaul1 I am using the internal DAC on my board, not external DAC.

Turning the I2S on and off does not cure the problem as its the starting of the DAC output that creates the click, transition from ground to mid-rail, and the stopping of DAC output that cause the transition from mid-rail to ground.
I notice that for the internal DAC setting that you are adding 0x80008000 to the I2S data which I think is the root cause, so is there any way that this addition can be applied to the I2S output on a constant basis ?

**Comment by schreibfaul1** [comment]
The decoders return an int16_t for each channel. However, the DAC only knows values ​​between 0 ... 0xFF, i.e. no negative ones. 
Maybe you can find a better solution. Feel free to write if you can improve something.
