### ISSUE TITLE
CH376

### ISSUE THREAD

**Issue by saschastreiber** [schreibfaul1/ESP32-audioI2S#447]
Hello,

i need a litlle help for using the CH376 for playing MP3 Files. I have a ESP32, with a PCM5102 , a ILI9488 Display and the CH376.
Everything runs.

Best regards Sascha

**Comment by mircose** [comment]
I tried to connect the CH376 with ESP32 via SPI thorout the library https://github.com/djuseeq/Ch376msc and the module work. 
I tried to create USB object:

Ch376msc flashDrive(5); // 5 is chipSelect
...
flashDrive.init();  //initialize
...
and play 
audio.connecttoFS(flashDrive, "test.mp3");

But I got error
