### ISSUE TITLE
Missing Data in the I2S Line for a ESP32-S2 Solo Module

### ISSUE THREAD

**Issue by ClaudioFoscan** [schreibfaul1/ESP32-audioI2S#453]
Hi 

i'm Using your Library with a ESP32 Wroom 32 Board and an MAX98357. 
Works as expected.

I like to use the same Setup with a ESP32-S2 Solo Board (cause of the internal USB-HW). the exactly same Code is used and produces some Dropouts in the I2S Data ... not the CLK-Line or the LRC-Line, they stay constant switching but on the Data-Line i see some missing Data between and the sound is broken. if i use an mp3 instead of the Webradio the speed is wrong with higher Bitrates and the Data is also dropping ...

is it possible that the ESP32-S2 has lower performance or are there some bugs for this SoC?

Anyone else the same expereance?

The used example Code :
`
#include "Arduino.h"
#include "WiFi.h"
#include "Audio.h"

//Digital I/O used  //Makerfabs Audio V2.0
#define I2S_DOUT 22
#define I2S_BCLK 26
#define I2S_LRC 25

Audio audio;

String ssid =     "****";
String password = "****";

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("Wroom Test with I2c");

  Serial.print("I2C init ... ");
  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
  audio.setVolume(5); // 0...21
  Serial.println("done");

  WiFi.disconnect();
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid.c_str(), password.c_str());
  while (WiFi.status() != WL_CONNECTED) delay(1500);
  Serial.println("wifi connectet...");

  Serial.print("Connect to SRF3 ... ");
  audio.connecttohost("https://stream.srg-ssr.ch/drs3/mp3_128.m3u");
  Serial.println("done");
}

void loop() {
  // put your main code here, to run repeatedly:
  audio.loop();
}

// optional
void audio_info(const char *info){
    Serial.print("info        "); Serial.println(info);
}
void audio_id3data(const char *info){  //id3 metadata
    Serial.print("id3data     ");Serial.println(info);
}
void audio_eof_mp3(const char *info){  //end of file
    Serial.print("eof_mp3     ");Serial.println(info);
}
void audio_showstation(const char *info){
    Serial.print("station     ");Serial.println(info);
}
void audio_showstreamtitle(const char *info){
    Serial.print("streamtitle ");Serial.println(info);
}
void audio_bitrate(const char *info){
    Serial.print("bitrate     ");Serial.println(info);
}
void audio_commercial(const char *info){  //duration in sec
    Serial.print("commercial  ");Serial.println(info);
}
void audio_icyurl(const char *info){  //homepage
    Serial.print("icyurl      ");Serial.println(info);
}
void audio_lasthost(const char *info){  //stream URL played
    Serial.print("lasthost    ");Serial.println(info);
}
void audio_eof_speech(const char *info){
    Serial.print("eof_speech  ");Serial.println(info);
}
`

**Comment by schreibfaul1** [comment]
Dual core MC is required, please use an ESP32 or ESP32-S3
