### ISSUE TITLE
HIRES player

### ISSUE THREAD

**Issue by mircose** [schreibfaul1/ESP32-audioI2S#454]
Hi,
I Play WAV and FLAC (ESP32 with PSRAM + DAC PCM1502) up to 16bit 2ch 44,1KHz without problem, but:

WAV 24bit 2ch 88,2KHz NOPLAY
info        Reading file: "/David Elias (24-88.2).wav"
info        FormatCode: 1
info        DataRate: 529200
info        DataBlockSize: 6
info        BitsPerSample: 24
info        BitsPerSample is 24,  must be 8 or 16
info        Closing audio file

FLAC 24bit 2ch 88,2KHz NOPLAY
info        Reading file: "/David Elias (24-88.2).flac"
info        FLACDecoder has been initialized, free Heap: 158652 bytes
info        Content-Length: 114664543
info        FLAC maxBlockSize: 2048
info        FLAC maxFrameSize: 9632
info        FLAC sampleRate: 88200
info        FLAC numChannels: 2
info        Closing audio file

Are there some option to play HIRES files (24bit 88,2KHz) or there is a limit for ESP?

**Comment by schreibfaul1** [comment]
Yes, there is a limit. To save memory, a sample can only consist of 8 or 16 bits.
