### ISSUE TITLE
MP3s not playing in certain circumstances

### ISSUE THREAD

**Issue by ConnalM** [schreibfaul1/ESP32-audioI2S#464]
Hi,

I have used the Talking Clock as the basis of a project and it works fine the code is in isolation. ie if there is nothing else going on in the programme. However, the programme I am trying to insert it into is somehow 'blocking' the playing of the file.

![image](https://user-images.githubusercontent.com/71526951/212365221-3b387881-f81f-4e8c-b940-3775aadee5ae.png)

The correct file is being selected to play but doesn't. I think I have seen this happen, if another file is selected to play almost instantly but this shouldn't be happening here. Not only does the file not play, it prevents the rest of the calling method to stop too.

Any suggestions?

Thanks, Connal

**Comment by schreibfaul1** [comment]
If you want to play multiple audio files in a row, then control them from loop() and use flags at EOF. This will work, but you will always have a gap between files.
I posted an example that works with GoogleTTS. Maybe that's an alternative.
https://github.com/schreibfaul1/ESP32-audioI2S/tree/master/examples/time_announcement

**Comment by ConnalM** [comment]
Thanks - I will give it a try but I need it to work outside the loop. It's so frustrating, as I had it working at one point and can't remember what I did. Thanks for the information.
