### ISSUE TITLE
Support for OPUS codec

### ISSUE THREAD

**Issue by aidam38** [schreibfaul1/ESP32-audioI2S#468]
Hello, are there any plans to support the OPUS codec (would allow playing audio from YouTube).

**Comment by schreibfaul1** [comment]
I adapted the decoder of the Xiph.Org Foundation to the ESP32 and removed all ballast. This works quite well in a standalone project (see https://github.com/schreibfaul1/ESP32-Opus-Player.git). However, this consumes so many resources that it cannot be used in the audioI2S library.

**Comment by aidam38** [comment]
Hmm, how hard would it be to adapt the networking code from ESP32-audioI2S to work with ESP32-Opus-Player, so that opus audio can be played from a URL?

**Comment by aidam38** [comment]
^made this into an issue here https://github.com/schreibfaul1/ESP32-Opus-Player/issues/1
