### ISSUE TITLE
Slowly pulsing noise when playing mp3 (but not aac)

### ISSUE THREAD

**Issue by redfast00** [schreibfaul1/ESP32-audioI2S#479]
I'm trying to play an MP3 file on SPIFFS. The code plays the file, but there's slow, pulsing noise. This is both when playing from internet streams, as when playing from SPIFFS. When I use an AAC stream, I don't have this problem.

I'm using the Lolin S2 mini board and had to change the pins:

```
#define I2S_DOUT      9
#define I2S_BCLK      7
#define I2S_LRC       6
```

I'd prefer to use MP3, since this seems to compress better and I'd be able to fit more audio on the board.

**Comment by redfast00** [comment]
@HelioDB do you also have this issue?

**Comment by redfast00** [comment]
@HelloDB do you also have this issue?

**Comment by schreibfaul1** [comment]
The ESP32-S2 only has one core, that won't work. Please use an ESP32.

**Comment by redfast00** [comment]
Oh, okay, thanks for the information. Would you accept a PR that adds this to the readme?
