### ISSUE TITLE
how to use PT8211 DAC

### ISSUE THREAD

**Issue by emid-alipour** [schreibfaul1/ESP32-audioI2S#506]
Hi
PT8211 is a dual channel low cost 16 bit Digital-to-Analog.
but your code need 24bit DAC,
how can I to change your code for 16bit DAC.
Regards.

**Comment by schreibfaul1** [comment]
The DACs used here are all 16 bit. The difference between PT8211 and the others like PCM5102 is the order in which the bits are read. It’s digital input timing format is Least Significant Bit Justified (LSBJ), or so called Japanese input format.

**Comment by emid-alipour** [comment]
Thanks' lot for your reply,
how can I change code for pt8211?

**Comment by TheAnimatrix** [comment]
`audio.setI2SCommFMT_LSB(true);`
after you set audio.setPinout ...
