### ISSUE TITLE
Greater consumption of heap

### ISSUE THREAD

**Issue by Avenitos** [schreibfaul1/ESP32-audioI2S#519]
Thank you for the library!

Now I use ESP8266Audio, but apparently they stopped developing it, according to this I am looking for a replacement.

But faced with a problem that does not allow you to switch to ESP32-audioI2S, this is a huge consumption of heap, which leaves no memory for my tasks. I use PSRAM.

Compared to the old one, this is somewhere + 60kb during playback, with which high consumption even before starting and after the end of playback via stopSong (), memory is not returned.

What can I do?

**Comment by schreibfaul1** [comment]
In the test environment, depending on the decoder, I have about 180KB of free heap with PSRAM (Arduino V2.0.6). Where possible, I swapped out memory to PSRAM. The behavior you describe looks like heap fragmentation.
