### ISSUE TITLE
Buffer for online radio?

### ISSUE THREAD

**Issue by rtek1000** [schreibfaul1/ESP32-audioI2S#53]
During playback of online radio, there are some interruptions due to the use of the internet band.

Would it be possible to add a buffer of about 5 seconds to avoid this problem?

**Comment by schreibfaul1** [comment]
The memory is limited. In many applications, the library does not run alone on the ESP32. Free heap under 80kBytes lead to instability in my experience. PSRAM would reduce the speed by 10% -20%. If you increase the memory, consider that a pointer is passed to the decoder on which at least one complete (aac or mp3) frame must be present.
