### ISSUE TITLE
connecttospeech(const char* speech, const char*)   add float ttsspeed parameter

### ISSUE THREAD

**Issue by jolugama** [schreibfaul1/ESP32-audioI2S#535]
Hello. The library is amazing, and it works great, but it would be great if a float parameter ttsspeed default to 1 was added, so we could change the speed, which is sometimes very useful to set to 0.1. Thank you. 🤠

**Comment by schreibfaul1** [comment]
You can change the speed at runtime. I guess the SampleRate of GoogleTTS is always 24000/s, then you could add this line in the loop():

`static bool f = false; if(audio.getSampleRate()== 24000 &&  !f) {audio.audioFileSeek(1.5); f = 1;}`
