### ISSUE TITLE
Better_WiFi_throughput example crashed with watchdog triggered on CPU 1

### ISSUE THREAD

**Issue by 0x0fe** [schreibfaul1/ESP32-audioI2S#539]
From a newly setup PIO, i just built the [Better_WiFi_throughput](https://github.com/schreibfaul1/ESP32-audioI2S/tree/master/examples/Better_WiFi_throughput) example, flashed to an ESP32D0WDR2 (V3) and got watchdog triggered on CPU 1.

![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/89607149/09fb6cda-695c-466a-b7a0-9edf9a1f87c8)

After adding disableCore1WDT(); to temporarly go around the issue, it append to fail to read the stream.

![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/89607149/4ef7680f-9a64-4fec-a56b-085f1861f157)

**Comment by schreibfaul1** [comment]
Jumping back to the Arduino Loop Task takes too long.
For testing you can disable the WDT1 in
menuconfig -> component config -> ESP System Settings

**Comment by 0x0fe** [comment]
thank you, so i assume it should be disabled during bootup and then reenabled just at the end of the setup.
