### ISSUE TITLE
Re start player when changing station internet radio

### ISSUE THREAD

**Issue by Andy-droid** [schreibfaul1/ESP32-audioI2S#546]
I'm receiving this error probably just an incompatible or broken URL.
however it doesn't clear when I select another URL. 
The last working URL is still playing but i cant move on to any other stations.
Is there any way to re start the player each time I select a new station. I'm just changing the URL in audio.connecttohost(station_url);

[413769][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():264]: (-32512) SSL - Memory allocation failed
[413769][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -32512

**Comment by GyverLibs** [comment]
@Andy-droid try to pauseResume, connecttohost, and pauseResume again. Its a crutch but works for me...
