### ISSUE TITLE
SPDIF output?

### ISSUE THREAD

**Issue by pwilkowski** [schreibfaul1/ESP32-audioI2S#549]
Hello, would it be possible to output to I2S as spdif?
Ive seen other libraries do it, i even have working example here: 
https://github.com/pschatzmann/ESP32-A2DP

Confirmed it works with Esp32 and bluetooth, however i wanted to have playback from SD card

**Comment by schreibfaul1** [comment]
SPDIF is quite doable. I don't want to expand the library with additional functions, so the in-house development remains. The same applies to A2DP Source and Sink. Here I would like to refer to the ESPuino project that can serve as an example for the use of BT. https://github.com/biologist79/ESPuino
