### ISSUE TITLE
Would it be possible to save the TTS voices on the SD card?

### ISSUE THREAD

**Issue by rtek1000** [schreibfaul1/ESP32-audioI2S#55]
A few years ago, I made a program (in Python) that saved the voice mp3 file for offline use, because sometimes it may be unavailable to the internet, or it needs to operate offline full time.

This site helps you to store the audio file for offline use:
[https://ttsmp3.com/](https://ttsmp3.com/)

**Comment by SymbolCsaba** [comment]
Little advertising but very useful! Thx!
