### ISSUE TITLE
onError(): [main] MP3 host error DNS failed

### ISSUE THREAD

**Issue by Ephesian** [schreibfaul1/ESP32-audioI2S#564]
Hi 
I am trying to connect to an internet radio that only has an ip address not a DNS entry and I get the following message

onError(): [main] MP3 host error DNS failed, which is what I would expect from giving IP address to DNS.

The radio is[ ](https://www.bvharmonyradio.com/) but stream is (http://192.111.140.11:8272/stream)

I suspect that no check is done and code assumes DNS in connecttohost

Eph.

**Comment by schreibfaul1** [comment]
If I go to their website and click on the player I also find the IP address.
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/26044260/994dba64-c731-41ae-9cf9-4c9ab3b147e1)

The connection works correctly.
````
23:24:07 AUDIO_info:  Connect to new host: "http://192.111.140.11:8272/stream"
23:24:07 AUDIO_info:  buffers freed, free Heap: 166083 bytes
23:24:07 AUDIO_info:  Connection has been established in 171 ms, free Heap: 165759 bytes
23:24:08 bitRate:     128Kbit/s
23:24:08 bitRate:     128Kbit/s
23:24:08 icy-descr:   A Mix of Blues Jumps, Rock N Roll, Vocal Groups & Early 60's
23:24:08 AUDIO_info:  icy-name: Rockin Rhythm and Blues Radio
23:24:08 StationName: Rockin Rhythm and Blues Radio
23:24:08 icy-url: ..  http://www.bvharmonyradio.com
23:24:08 AUDIO_info:  MP3Decoder has been initialized, free Heap: 164495 bytes , free stack 5104 DWORDs
23:24:08 lastURL: ..  http://192.111.140.11:8272/stream
23:24:08 AUDIO_info:  stream ready
23:24:08 AUDIO_info:  syncword found
````
No DNS is needed. Can the problem lie in the network configuration?
