### ISSUE TITLE
Some Streaming URLs do not work

### ISSUE THREAD

**Issue by Hellmas83** [schreibfaul1/ESP32-audioI2S#566]
Hi Thank you for this great Libray. It works realy good. But I have some Streaming urls That do not work and i dont know way?
Can you help me?
This is one of them. In my Browser it works good but on my web radio its do no working.

https://rozhlas.stream/vltava_high.aac

**Comment by schreibfaul1** [comment]
The stream works.
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/26044260/8425961c-91f2-424f-a312-07bcbec12b50)
Maybe settings in the router or firewall?
