### ISSUE TITLE
Arduino 1.x reports 'plays all files in a directory' is an invalid project name

### ISSUE THREAD

**Issue by flywhc** [schreibfaul1/ESP32-audioI2S#567]
Arduino 1.8.19 pops up an error message that a project name may only contain letter and digits. "ESP32-audioI2S/examples/plays all files in a directory/" contains space characters that should be removed.

**Comment by hmax42** [comment]
yeah, i can confirm that

**Comment by schreibfaul1** [comment]
It may be that the file name is not accepted by the Arduino IDE. I removed the spaces.
