### ISSUE TITLE
Limit to required functionality

### ISSUE THREAD

**Issue by lowenna** [schreibfaul1/ESP32-audioI2S#568]
Fabulous library, thank you for writing. Are there any plans to make this modular/configurable in some way to limit the amount of overhead it takes compiling into a project. (I'm using platformio under VSCode if that makes a difference, not Arduino IDE). 

As an example, I am using it for playing MP3 from SD and have no need for FLAC/VORBIS/Streaming etc. Literally a no-frills MP3 from SD player and nothing else, not even meta-data.

Without the library included in a (reasonably large) project:
```Flash: [=====     ]  46.0% (used 963989 bytes from 2097152 bytes)```

With the library included in the same project:
```Flash: [=======   ]  65.3% (used 1369981 bytes from 2097152 bytes)```

Although I'm relatively new to the ESP32 and have much to learn, I'm not new to coding. The best part of 20% of flash for including the library seems a lot.

Thanks
John.

**Comment by schreibfaul1** [comment]
That's a good idea, but due to the many dependencies, it's not easy to delete unused decoders or SW areas. I could take this up later and solve it with preprocessor directives.
