### ISSUE TITLE
Music files stop before actual end

### ISSUE THREAD

**Issue by kiwi85** [schreibfaul1/ESP32-audioI2S#570]
I am using wrover chip with psram and Arduino ide. Everything works fine despite any mp3 file stops about 1 s before end. Also loop takes quite a while to restart the file.
Any ideas on how to address this issue ?

**Comment by schreibfaul1** [comment]
I have a test file here, 1KHz, 80% 0.8s pause, 0.2s tone, 5 times.
This works as expected.
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/26044260/f26ac4be-eb02-46d4-b0b6-d4062738e9c4)
[5pulse.wav.zip](https://github.com/schreibfaul1/ESP32-audioI2S/files/12257479/5pulse.wav.zip)

**Comment by lombyp** [comment]
Hello and congratulations for your work, I'm using wrover **https://www.makerfabs.com/eps32-audio-player.html** and Arduino IDE, I'm having a problem playing .wav files, every time I use the function **audio.setAudioPlayPosition(int);**  the playback of the song stops before its actual end, sometimes even halfway.
Have you already noticed this problem?
Can I call the function while the song is playing or do I have to pause it first?
to be honest I've tried them all but the problem still occurs.

**Comment by schreibfaul1** [comment]
Hello @lombyp,
I was able to simulate the error, especially with PSRAM and short files. Hope it works now.

**Comment by lombyp** [comment]
It works now! many thanks
