### ISSUE TITLE
How do I use the setAudioPlayPosition

### ISSUE THREAD

**Issue by AmirAmraei** [schreibfaul1/ESP32-audioI2S#577]
How do I use the following function?

bool setAudioPlayPosition(uint16_t sec);

**Comment by schreibfaul1** [comment]
The function can only be used in connection with local files on the SD card. When an audio file is played, its playing time is known via the bit rate and the size of the audio block. Then you can jump to a certain position within the file, e.g. the value 90 jumps to the position that corresponds to 1.5 minutes of playing time.
