### ISSUE TITLE
Possible data truncation in Vorbis Decoder

### ISSUE THREAD

**Issue by ma261065** [schreibfaul1/ESP32-audioI2S#580]
Hi,

Probably not a big deal, but I notice that in the definition of  `mdct_unroll_lap` that `in`, `right`, `w0` & `w1` are all of type `int`, but the parameters passed in (`s_dsp_state->work[i]`, `s_dsp_state->mdctright[i]`, `_vorbis_window(s_blocksizes[0] >> 1)` and                 
 `_vorbis_window(s_blocksizes[1] >> 1)` are all of type `int32_t`.

This could lead to data truncation if someone was compiling on a platform where `int` was only 16 bits

Can I suggest that the definition of `mdct_unroll_lap` be changed to:

`void mdct_unroll_lap(int n0, int n1, int lW, int W, int32_t *in, int32_t *right, const int32_t *w0, const int32_t *w1, short int *out,`
`int step, int start, /* samples, this frame */`
`int end /* samples, this frame */)`

**Comment by schreibfaul1** [comment]
thank you, I have corrected it

**Comment by ma261065** [comment]
Thanks!
