### ISSUE TITLE
Vorbis Decoder crash under low memory condition

### ISSUE THREAD

**Issue by ma261065** [schreibfaul1/ESP32-audioI2S#581]
I am running the Vorbis decoder on a system with a bunch of competing memory usage. It was crashing very randomly, and after a whole lot of debugging I found that it was happening on line 727:
`lengthlist = (char *)malloc(sizeof(*lengthlist) * s->entries);`

The malloc was randomly failing, and there is no check for a valid return, so the subsequent use of the NULL buffer would cause a crash.
The fix was to change it to use `__malloc_heap_psram()`

Suggestion - why not use `__malloc_heap_psram()` everywhere as there will be less likelihood of memory failures? Or, at least check for valid return values?

**Comment by schreibfaul1** [comment]
Hello Mike, if PSRAM is available, it should be used preferentially. I have made up for that in two places. Thank you very much for your advice.
