### ISSUE TITLE
" low stream, dropouts are possible"

### ISSUE THREAD

**Issue by Arielhh** [schreibfaul1/ESP32-audioI2S#582]
Will you be able to release a version for Arduino IDE that solves the problem of slow stream, dropouts are possible? 
Do you know why the same issue is not happening when streaming the same stations for example using a mobile phone app?

**Comment by schreibfaul1** [comment]
If you want to increase the data throughput, you must not use the pre-packaged Arduino versions. The parameters that are decisive for this can be found here: https://github.com/schreibfaul1/ESP32-audioI2S/tree/master/examples/Better_WiFi_throughput 
And a complete example here: https://github.com/schreibfaul1/ESP32-MiniWebRadio

**Comment by Arielhh** [comment]
Wolle, many thanks.
I saw these posts. The issue is the I am using an Arduino IDE.
I will try to port my code to PlatformIO and see if it works.
