### ISSUE TITLE
When Arduino-ESP32 is used as a component of ESP-IDF

### ISSUE THREAD

**Issue by vwwwvwww** [schreibfaul1/ESP32-audioI2S#590]
When Arduino-ESP32 is used as a component of ESP-IDF, does this mean that it is not possible to play music using this library?

**Comment by biologist79** [comment]
No, this works.
[ESPuino](https://github.com/biologist79/ESPuino) makes use of this library and recently it was shown that it works. It's just necessary to change the platform: https://github.com/biologist79/ESPuino/blob/dev/platformio.ini#L23
