### ISSUE TITLE
HLS Stream Support

### ISSUE THREAD

**Issue by Jerry-F-1** [schreibfaul1/ESP32-audioI2S#592]
Hi,  thanks for a great library which I have used to make several different radios, with ESP32 and external DAC.   While I live in Ireland, I like to listen to some of the BBC stations, particularly BBC4.  Unfortunately this year, BBC changed the codec for most of their stations and your library no longer works in those cases.  Do have any plans to include this support?

**Comment by schreibfaul1** [comment]
Yes, I know, BBC has switched to HLS and not all streams are receivable abroad. Here is an (incomplete) list of streams that work in Germany with the audioI2S lib.


http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_6music.m3u8		
https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_three.m3u8
https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_fourfm.m3u8
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d96000.norewind.m3u8		// BBC - Radio 1
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d48000.norewind.m3u8		// BBC - Radio 1
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_one_relax/bbc_radio_one_relax.isml/bbc_radio_one_relax-audio%3d48000.norewind.m3u8
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d48000.norewind.m3u8
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d48000.norewind.m3u8	// BBC - Radio 3
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d48000.norewind.m3u8	// BBC - Radio 3
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d48000.norewind.m3u	//8BBC - Radio 5 live
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_asian_network/bbc_asian_network.isml/bbc_asian_network-audio=48000.norewind.m3u8	// BBC - Radio Asian Network
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d48000.norewind.m3u8	// BBC - BBC World Service
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_essex/bbc_radio_essex.isml/bbc_radio_essex-audio%3d48000.norewind.m3u8	// BBC - BBC Essex
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_berkshire/bbc_radio_berkshire.isml/bbc_radio_berkshire-audio%3d48000.norewind.m3u8	// BBC - Radio Berkshire
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_bristol/bbc_radio_bristol.isml/bbc_radio_bristol-audio%3d48000.norewind.m3u8	// BBC - Radio Bristol
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_cambridge/bbc_radio_cambridge.isml/bbc_radio_cambridge-audio%3d48000.norewind.m3u8	// BBC - Radio Cambridge

**Comment by Arielhh** [comment]
Install VLC on your PC https://www.videolan.org/vlc/download-windows.html then download the m3u right click and open with VLC. once it starts playing go to media, open network stream. the URL will be there.

**Comment by Arielhh** [comment]
open notepad in your pc. download the first link you provided. once downloaded drag it to the open notepad and you will see a link http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d96000.norewind.m3u8. this link is playing for me.  I tried additional one from that list and it also worked http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewbbc1  You can get the same link if you open the downloaded file with VLC.
