### ISSUE TITLE
there is a limit of words for connecttospeech()?

### ISSUE THREAD

**Issue by alcarazolabs** [schreibfaul1/ESP32-audioI2S#597]
Hi dear and community, I'm having an issue with this library,.
All works fine when I set a  small word sentences to the connecttospeech function, for example this:

`  audio.connecttospeech("Hola saludos desde perú")`

However when I set this big word sentence:

` audio.connecttospeech("Estas son las noticias del diario la republica. Corte de luz en Chiclayo: ¿qué zonas serán afectadas el 10 de octubre?. Niño lidera banda musical en fiesta patronal de Lambayeque y causa furor: 'Talento en la sangre'. Señor de los Milagros en Chiclayo: ¿qué vías cerrarán en primer recorrido este sábado 7 de octubre?. Corte de luz en Chiclayo: ¿qué zonas serán afectadas el 8 de octubre?. Lambayeque: triaje de hospital en carpa y millonaria obra no concluye. Sujeto salió de la prisión para liderar red y robar S/560 mil en Lambayeque", "es");`
                  
the code throws this error:

```

info        buffers freed, free Heap: 205188 bytes
streamtitle HTTP/1.1 400 Bad Request
station     
icyurl
```

![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/7144988/1ee9059d-18c1-4fac-9eb1-a556a9a47a20)

I don't know why happens this. My main goal es always pass a big sentence to the connecttospeech() function. There is a limit for this? Or I should host my audio file here in github and then play it by using this library.

thanks so much.

**Comment by dominickairmyne** [comment]
> Hi dear and community, I'm having an issue with this library,. All works fine when I set a small word sentences to the connecttospeech function, for example this:
> 
> ` audio.connecttospeech("Hola saludos desde perú")`
> 
> However when I set this big word sentence:
> 
> ` audio.connecttospeech("Estas son las noticias del diario la republica. Corte de luz en Chiclayo: ¿qué zonas serán afectadas el 10 de octubre?. Niño lidera banda musical en fiesta patronal de Lambayeque y causa furor: 'Talento en la sangre'. Señor de los Milagros en Chiclayo: ¿qué vías cerrarán en primer recorrido este sábado 7 de octubre?. Corte de luz en Chiclayo: ¿qué zonas serán afectadas el 8 de octubre?. Lambayeque: triaje de hospital en carpa y millonaria obra no concluye. Sujeto salió de la prisión para liderar red y robar S/560 mil en Lambayeque", "es");`
> 
> the code throws this error:
> 
> ```
> 
> info        buffers freed, free Heap: 205188 bytes
> streamtitle HTTP/1.1 400 Bad Request
> station     
> icyurl
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7144988/273421114-1ee9059d-18c1-4fac-9eb1-a556a9a47a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjc0MTUsIm5iZiI6MTcxMDEyNzExNSwicGF0aCI6Ii83MTQ0OTg4LzI3MzQyMTExNC0xZWU5MDU5ZC0xOGMxLTRmYWMtOWViMS1hNTU2YTlhNDdhMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDMxODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMzYmEzZjRmZDZjOGNmNjY2MWMzZTMwMDBmOTBiNGUzNDdlNmFiMzIyZmM0NDM2MTZlOWU2NDJjZmFlMmM0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zkHcjpsPFbZFdlaZh1gjcJCuq5297JlXsdwvmW7Q5WU)
> 
> I don't know why happens this. My main goal es always pass a big sentence to the connecttospeech() function. There is a limit for this? Or I should host my audio file here in github and then play it by using this library.
> 
> thanks so much.

Did you ever figure this out? Having the same issue right now.
