### ISSUE TITLE
Unable to build Simple WiFI Radio

### ISSUE THREAD

**Issue by kuzmanzs** [schreibfaul1/ESP32-audioI2S#61]
Hi,
it looks like sketch is too big.. "Sketch uses 2263350 bytes (172%) of program storage space"
You can compile it?

**Comment by schreibfaul1** [comment]
Yes, set Partition Scheme "Huge App"
![image](https://user-images.githubusercontent.com/26044260/93123190-02dab080-f6c8-11ea-8ba3-6f583787069d.png)

**Comment by kuzmanzs** [comment]
super, thanks.
