### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by nodoubtman** [schreibfaul1/ESP32-audioI2S#622]
Hello i found another error in the new library v3.00

class Audio' has no member named 'i2s_mclk_pin_select

can you help?
Thanks.
Marc.

**Comment by schreibfaul1** [comment]
Espressif uses IDE 5.1 ​​with Arduino V3. This leads to many changes in the I2S driver. In this context, I removed old code (everything for Arduino 2.0.8), so 'i2s_mclk_pin_select' no longer exists. If you need MCLK then you can set the pin in “setPinout()”. for example: ` audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT, I2S_MCLK);`

**Comment by nodoubtman** [comment]
thanks!
