### ISSUE TITLE
Sponsorship possible?

### ISSUE THREAD

**Issue by somebox** [schreibfaul1/ESP32-audioI2S#625]
I haven't posted any issues before, because I've been very happy to use this library in my ESP32 audio projects, mostly restoring old radios to be retro internet-streaming awesome. End of year and all, and I thought to sponsor this project, but couldn't see how?Github? Patreon? or just a coffee? Cheers and thanks for sharing this wonderful hackers gem.

**Comment by schreibfaul1** [comment]
Thank you for your offer. I'm glad you're using this library to restore old radios.
This is a non-commercial project and does not have to generate revenue.
