### ISSUE TITLE
More Vorbis files that won't play

### ISSUE THREAD

**Issue by ma261065** [schreibfaul1/ESP32-audioI2S#650]
Hi,

I found two more Vorbis files that won't play, but do play in other players.

https://archive.org/download/gd1982-04-11.sbd.miller.108852.flac16/gd82-04-11d1t02.ogg
and
https://archive.org/download/gd1978-08-30.s2.sbd.miller.110151.flac16/gd78-08-30d3t03.ogg

Both seem to have the same problem in that there is excessive padding before the third OggS marker.

The third marker is at 0x1800, so the code in `VORBISparseOGG(uint8_t *inbuf, int *bytesLeft)` that calls `VORBIS_specialIndexOf()` doesn't find it.

I found that changing the line to:
`int idx = VORBIS_specialIndexOf(inbuf, "OggS", 8192);`
allows them to be played.

**Comment by ma261065** [comment]
@schreibfaul1 what do you think about these? Is it worth adjusting the code to allow them to play?

**Comment by schreibfaul1** [comment]
Oh, I think I missed your issue. I'll have a look at it soon.

**Comment by schreibfaul1** [comment]
And another error fixed. Thank you for your support.
