### ISSUE TITLE
MCLK Signal

### ISSUE THREAD

**Issue by Arielhh** [schreibfaul1/ESP32-audioI2S#654]
Is there a way to get the MCLK of the I2S signal?

**Comment by Arielhh** [comment]
Wolle, many thanks 🙏

**Comment by Arielhh** [comment]
For the MCLK using ESP32-S3 can any port be used or it is limited to GPIO0? I have tried GPIO10 but with not much success.

**Comment by schreibfaul1** [comment]
MCLK is not limited to GPIO0

**Comment by Arielhh** [comment]
Ok, thanks.

**Comment by Arielhh** [comment]
It's working perfectly.
