### ISSUE TITLE
audio.connecttospeech() function change request

### ISSUE THREAD

**Issue by mmar22** [schreibfaul1/ESP32-audioI2S#668]
Now google return mono and 24000Hz samplerate. Can you change or add code to mix speech to actual sound played or resample it to 48k ? Or ask google to other samplerate?

**Comment by schreibfaul1** [comment]
Hi mmar22,
I don't know. We send the URL encoded string to GoogleTTS and get an mp3 stream back. The string is limited to about 200 characters in the free version.
