### ISSUE TITLE
Cant stream from secure servers

### ISSUE THREAD

**Issue by dgrogandesign** [schreibfaul1/ESP32-audioI2S#67]
HI there. I have managed to stream from the included servers and some other http servers but whenever i try to stream from an https server i get the error: "audio/mp3 seen, info unknown audio format " - is this a limitation of the software or am i doing something wrong? thanks.

**Comment by BCsabaEngine** [comment]
I can download/play from https server without problem. Now i stored MP3 as static file, so Apache send proprietrary mime info. Can you send a sample https URL in private?

**Comment by schreibfaul1** [comment]
mime type audio/mp3 is now supported

**Comment by BCsabaEngine** [comment]
Thank you on behalf of dgrogandesign!

**Comment by dgrogandesign** [comment]
> I can download/play from https server without problem. Now i stored MP3 as static file, so Apache send proprietrary mime info. Can you send a sample https URL in private?

Hi, sorry for late replys. I have actually got it working with https now, to be specific, the problem i was having was trying to access files stored on an amazon AWS server. I tried storing it on a google cloud server and it works. problem is that i would rather use the amazon server...

**Comment by schreibfaul1** [comment]
How does the access to AWS work, maybe the authentication fails? What is logged in audio_info ()?
