### ISSUE TITLE
DLNA rendere (target) with FLAC support

### ISSUE THREAD

**Issue by tibi03** [schreibfaul1/ESP32-audioI2S#677]
hello, i am trying to use an esp32 with DAC PCM5102A as a dlna renderer as a target only but i cannot find it on my network with your example.

another thing is that i can browse my local dlna server but cannot play flac.

In the end i want to use it as a cheap dlna rendered instead of a raspberry pi and use a smartphone to control the stream.

thanks

![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/46863798/83f5dc83-f749-491a-9a74-185d4a3efce7)

**Comment by schreibfaul1** [comment]
The DLNA servers must be in the home network. They are reached via a MULICAST on ports 1900 and 8888. Perhaps the firewall is preventing the connection. CT audio/x-flac works with a more recent version, I have updated the platformio.ini.

**Comment by tibi03** [comment]
the dlna server is reachable and i can browse the content from esp32 web gui but esp32 itself is not visible on the network as a renderer like volumio in pic below:
![Screenshot_20240212-212436](https://github.com/schreibfaul1/ESP32-audioI2S/assets/46863798/625697b5-a251-4163-9656-8652db5432bf)

i can play music and radio from hi-fi cast app on android on volumio but esp32 is not available as a playback device.

**Comment by tibi03** [comment]
i found this project but seems to be not updated. i think is exactly what i need https://github.com/while0l1/ESP32-DLNA-Render

**Comment by tibi03** [comment]
or this one https://github.com/alxvasilev/net-player-esp32
