### ISSUE TITLE
M3U8 noisy

### ISSUE THREAD

**Issue by FatherMarco1971** [schreibfaul1/ESP32-audioI2S#685]
Using releas 3.0.8 with this stream

http://streamcdnm2-4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/play1.m3u8
Cuase the stop after the (perfect) reproduction of 3 ts.
Using the 3.0.8p it doesn't stop but the sound is orrible and full of interruption and glitch and the log is full of:

AAC decode error -15 : NCHANS_TOO_HIGH

I'm not good enough to debug your code but if you need help for testinf i'll do my best

**Comment by schreibfaul1** [comment]
There is other information in the stream contained. Could be a video sequence, I don't know. I copied two streams from the website, [from the station](https://www.deejay.it/webradio/), which are pure audio https://streamcdnf25-4c4b867c89244861ac216426883d1ad0.msvdn.net/webradio/deejay80/live.m3u8 https://streamcdnf24-4c4b867c89244861ac216426883d1ad0.msvdn.net/webradio/deejayonelove/live.m3u8

**Comment by FatherMarco1971** [comment]
I understand.
Thank you very mutch.

**Comment by FatherMarco1971** [comment]
I think the problem is not the presence of any video but that the AAC decoder can't process correctly audio.
Fromm VLC i can see for this [http://streamcdnm2-4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/play1.m3u8](url) stream:
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/56395249/694e93a6-ee42-4e86-8ffa-9e24f6e9a050)

for this [https://streamcdnf24-4c4b867c89244861ac216426883d1ad0.msvdn.net/webradio/deejayonelove/live.m3u8](url):
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/56395249/b0360f64-389a-4752-9602-dfe2542557d7)

I think the problem is that "extensio AAC: SBR".
The courios thing is that  the version 3.0.8 sound perfectly but stop after 3 .ts.

**Comment by schreibfaul1** [comment]
Here is a recording from the link above als RAW file
[raw.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14484638/raw.txt)
According to the specification, a ts packet is exactly 188 bytes long. This is not the case here. I don't know what is transmitted between the packets. Maybe someone who reads here can help.
![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/26044260/af53fc4a-151d-4d53-aa45-94899520efde)

**Comment by FatherMarco1971** [comment]
Rolling back to this release of your lib (10 Jan 2024):

[https://github.com/schreibfaul1/ESP32-audioI2S/tree/17f0e0468ee862b9ea1d4b6b85d91b599535acdc](url)

Everething work like a charme!!
So I was wrong your code can work but some chenges done from 10 Jan to today have break something!!!!!

I try my best but your code is too complex for my capability to understand where the problem is but, if you need log or testing i'm happy to do my best.

**Comment by FatherMarco1971** [comment]
I've found what cause the bug @schreibfaul1
I will create a pull request so you can review it and accept or modify it.
