### ISSUE TITLE
Memory limitation issues

### ISSUE THREAD

**Issue by hcsteen** [schreibfaul1/ESP32-audioI2S#708]
Excellent library!
However I have an issue with memory allocation.
I have made a simple internet radio using a small oled-display and SD-card for station lists/URL.
It all works like a charm using http, but when I try to connect to a station using https, it will not work.
The error message on the monitor is: "not enough memory to allocate mp3decoder buffers"
The even more simple internet radio example supplied with the library works just fine with both http and https.
Most likely I have used all available memory space with my programming.
I've read the available documentation, but are unable to find much about memory allocation.
Is it possible to tweek the memory to make room for my programming and https ?

**Comment by schreibfaul1** [comment]
The decoders need storage space. This leaves less for your own project. If you activate PSRAM, this is automatically recognised and the memory is allocated to PSRAM.
