### ISSUE TITLE
PSRAM leakage?

### ISSUE THREAD

**Issue by SanZamoyski** [schreibfaul1/ESP32-audioI2S#710]
Hi!

I think that something is not ok here. When song ends or is rewinded to next my free PSRAM lowers.
I've left my player overnight and result is recorded in attached txt file.

[[24.03.19]-mod.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789437/24.03.19.-mod.txt)

I can not provide at the moment right software version, since it was modified since then. But I'll try to give You some useful  informations. I'm using platformio:

[platformio.ini.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789484/platformio.ini.txt)
[UAP_PinDef.inch.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789493/UAP_PinDef.inch.txt)
[UAP_SdArrays.inc.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789500/UAP_SdArrays.inc.txt)
[UAP_DBG.inc.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789510/UAP_DBG.inc.txt)
[main.cpp.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789522/main.cpp.txt)
[UAP_CoreLoop.inc.txt](https://github.com/schreibfaul1/ESP32-audioI2S/files/14789532/UAP_CoreLoop.inc.txt)

Can we delete those files after solving/nofix this problem?

Is there anything wrong in my source or this is a bug? Sorry for the mess in source.

All my audio files are full-albums flac.

Best regards!

**Comment by schreibfaul1** [comment]
The memory leak will have existed for a long time, the samplesBuffer was not released correctly. Thanks for the tip.

**Comment by SanZamoyski** [comment]
Can You provide some workaround?
I.e. what should I do if PSRAM gets too low to play another song?

i```
f(ESP.getFreePsram() < 32*1024){
  //do something smart here...
}
```

Currently I'm rebooting ESP when I realise there is PSRAM shortage.

**Comment by schreibfaul1** [comment]
The loss was about 64KB at each initialisation of the FLAC decoder. I used `ESP.getFreePsram()` too  to plug the leak.

**Comment by SanZamoyski** [comment]
but how?

**Comment by FatherMarco1971** [comment]
@SanZamoyski  he has committed a correction or i'm not understandign what you are asking for?

![image](https://github.com/schreibfaul1/ESP32-audioI2S/assets/56395249/75d6b7da-897a-4ad5-94be-a2670e0de7df)

**Comment by PMKrol** [comment]
I have checked it. Still free PSRAM lowers each time I play next flac.

**Comment by SanZamoyski** [comment]
Updated libraries, it is in fact working now. Thanks!
