### ISSUE TITLE
How to reduce library size?

### ISSUE THREAD

**Issue by AnatolyNevzoroff** [schreibfaul1/ESP32-audioI2S#719]
Great library!
But very hard! The library takes up about 90% of the memory. I have never used and do not intend to use opus_decoder.h and vorbis_decoder.h.
These decoders take up memory. How to exclude them from the library. If you use ESP32 only for radio, you can exclude flac_decoder.h, but how to do this?
I know a project that uses your library without the specified decoders. The files: audio.cpp and audio.h are modified, but I can’t understand how this was done.
Help me please!

**Comment by schreibfaul1** [comment]
You probably mean the flash memory. Please try another partition table, such as "Huge App (3MB no OTA/ 1MB SPIFFS)"

**Comment by AnatolyNevzoroff** [comment]
Yes, I mean memory for recording a sketch.
I understand that you will not exclude decoders just because “someone asked,” but it seems to me that sooner or later, such a need will still arise. Think about this question.
The option you suggested does not suit me...

**Comment by whitevast** [comment]
The question is relevant. Why keep unnecessary decoders in memory to the detriment of OTA?

**Comment by AnatolyNevzoroff** [comment]
Конечно актуален!



С уважением, *Невзоров Анатолий Юрьевич*.
 *+79882377098*


вт, 23 дек. 2025 г., 09:36 Александр ***@***.***>:

**Comment by schreibfaul1** [comment]
There is a fork that does this. Changes applied to ESP32-audioI2S (v3.4.4d)#1237

stef-ladefense has some good ideas.
I will implement most of them, not 1:1, but only in the coming days.
Please use for the time being https://github.com/stef-ladefense/ESP32-audioI2S/tree/master
