### ISSUE TITLE
Send output to other amplifier

### ISSUE THREAD

**Issue by fmarzocca** [schreibfaul1/ESP32-audioI2S#724]
Is there a way to send analog audio to an external amplifier? I am using MAX98357, but I like to grab analog audio and input it into another amplifier.

**Comment by Arielhh** [comment]
> Is there a way to send analog audio to an external amplifier? I am using MAX98357, but I like to grab analog audio and input it into another amplifier.

The best way is to replace it with pcm5102a, this module is stereophonic and has a line out jack which you can use to connect to your amp. there is even version with RCA L/R out ports
