### ISSUE TITLE
when i add this lib  into my  esp32s3box,  build errors 

### ISSUE THREAD

**Issue by justdomyself** [schreibfaul1/ESP32-audioI2S#725]
In file included from .pio/libdeps/esp32s3box/ESP32-audioI2S/src/Audio.cpp:9:
.pio/libdeps/esp32s3box/ESP32-audioI2S/src/Audio.h:16:10: fatal error: WiFi.h: No such file or directory

**Comment by schreibfaul1** [comment]
WiFi.h is part of the "Arduino core for the ESP32", https://github.com/espressif/arduino-esp32
