### ISSUE TITLE
radio using HLS not working

### ISSUE THREAD

**Issue by lidense** [schreibfaul1/ESP32-audioI2S#731]
I would like to listen to this radio:
https://radioitaliasmi.akamaized.net/hls/live/2093120/RISMI/master.m3u8
Works with vlc but not with this library, any ideas?

**Comment by lidense** [comment]
Do you think there might be a workaround? It works well with vlc and mpd...

**Comment by schreibfaul1** [comment]
When I call up the URL https://radioitaliasmi.akamaized.net/hls/live/2093120/RISMI/master.m3u8, the m3u8 file is transferred and the connection is terminated. The connection remains open for the URLs to the audio sequences, as expected. Unfortunately, the ESP32 takes too long to establish an https connection (it will be fast enough on a PC). If anyone knows a solution, please post here.

**Comment by lidense** [comment]
I gathered that the /.../ is a relative link so I put this as the address for audio.connecttohost:
"https://radioitaliasmi.akamaized.net/hls/live/2093120-b/RISMI/stream01/streamPlaylist.m3u8"
And now IT WORKS perfectly!!

**Comment by schreibfaul1** [comment]
great! the connection is not terminated after receiving the m3u8 playlist.
The reason for this is that it can take a few seconds to establish a TLS connection. The WiFiClientSecure blocks during this time.
The WiFiClient can be replaced by the HTTPClient without blocking. But there is nothing for WiFiClientSecure and I am not familiar with SSL.
