### ISSUE TITLE
Frequent timeouts do not exist in version 3.0. setConnectionTimeout has no effect.

### ISSUE THREAD

**Issue by genicsoft** [schreibfaul1/ESP32-audioI2S#733]
Frequent timeouts do not exist in version 3.0. setConnectionTimeout has no effect.

  [103872][E][Audio.cpp:3684] parseHttpResponseHeader(): timeout

**Comment by schreibfaul1** [comment]
This is not suitable for this, this is the parameter for the WiFiClient or WiFiClientSecure  when establishing a connection   `NetworkClient::connect(const char *host, uint16_t port, int32_t timeout_ms)`

timeout in parseHttpResponseHeader() means there is no response from the host
