### ISSUE TITLE
Correct close when play known length sound

### ISSUE THREAD

**Issue by BCsabaEngine** [schreibfaul1/ESP32-audioI2S#74]
You lib works perfectly, but when sound playing arrives at the end of sound input (known length of mp3), it does not close buffers properly. And there some noise sound (Grrbrrrgrr).

I have tried to solve it by closing song with your method: StopSong() here (instead of simply set mfrunning to false)

sprintf(chbuf, "End of webstream: %s", m_lastHost.c_str());
if (audio_info)
  audio_info(chbuf);
if (audio_eof_stream)
  audio_eof_stream(m_lastHost.c_str());

//m_f_running = false;
stopSong();

It works. Can you "merge" it to the project?

**Comment by schreibfaul1** [comment]
thanks!

**Comment by BCsabaEngine** [comment]
Thank you
