### ISSUE TITLE
speech / host does not work together

### ISSUE THREAD

**Issue by aber68** [schreibfaul1/ESP32-audioI2S#741]
hello, why does this lines not work on arduino ESP32-S3? thx 4 help br andreas

... code
**audio.connecttospeech("Radio abc"), "de");   // will never heard
audio.connecttohost(".... radio stream url");**
... code

connecttospeech works only if called without following connecttohost. i want to realize an annoncement of an radio station before playing the stream

**Comment by schreibfaul1** [comment]
1) audio.connecttospeech("Radio abc"), "de"); 
2) waiting for audio_eof_speech()
3) audio.connecttohost(".... radio stream url");

**Comment by aber68** [comment]
sorry for bother you, but how to code this line #2?

**Comment by aber68** [comment]
this will probably work, but i need to choose many radio stations. is there an other possibility to wait on eof_speech? i tried with a flag within audio_eof_speech(const char *info) but this doesn't work

**Comment by ivuslat** [comment]
audio.connecttospeech("Radio abc"), "de"); // will never heard

    while (audio.isRunning()) {
    audio.loop();
  }

audio.connecttohost(".... radio stream url");

**Comment by aber68** [comment]
thanks, works as well!
