### ISSUE TITLE
audio fails in some positions

### ISSUE THREAD

**Issue by lidense** [schreibfaul1/ESP32-audioI2S#760]
I have a webradio using this nice library running on an M5stack Core2 with a small external DAC hooked to an amplified speaker with a cable audio jack 3.5.
This device works well for the dozen or so mp3 or HLS radios stations that I have in my platformio sketch but in certain positions sound stops or runs intemittently with a period of about 1 sec.
If I move the device in a different position it goes back to working. It doesn't seem to be a bad contact because the device and its DAC are held steady in a box.  Wifi signal seems to be sufficient.  
It reminds me of issues like going into some kind of resonance or interference in certain  positions, any idea?
Thanks

**Comment by lidense** [comment]
...the terminal gives this error message when the above happens:
[ 80634][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263

**Comment by schreibfaul1** [comment]
> [ 80634][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263

I2C is probably used for communication with an external DAC? I have no idea, maybe an ACK problem.

If dropouts occur with HLS, which is quite possible, you can double the DMA buffer. While a new data packet is being fetched and decoded, the DMA must bridge the time. Unfortunately, the DMA in the ESP32 is very small.

**Comment by lidense** [comment]
OK, thanks.
Regards

----- Mail d'origine -----
De: Wolle ***@***.***>
À: schreibfaul1/ESP32-audioI2S ***@***.***>
Cc: lidense ***@***.***>, Author ***@***.***>
Envoyé: Tue, 04 Jun 2024 21:58:13 +0200 (CEST)
Objet: Re: [schreibfaul1/ESP32-audioI2S] audio fails in some positions (Issue #760)

> [ 80634][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263

I2C is probably used for communication with an external DAC? I have no idea, maybe an ACK problem.

If dropouts occur with HLS, which is quite possible, you can double the DMA buffer. While a new data packet is being fetched and decoded, the DMA must bridge the time. Unfortunately, the DMA in the ESP32 is very small.

**Comment by lidense** [comment]
what is the maximum size of dma? 
And of dma count?
Thanks
