### ISSUE TITLE
Misuse of Mutex

### ISSUE THREAD

**Issue by MeAndy56** [schreibfaul1/ESP32-audioI2S#761]
Hallo, I used your simple WIFI Radio. It worked fine, then I expanded my Code to read *.mp3 from SD. Worked fine. But if I heared WIFI musik then SD musik and switched back to WIFI musik the audio loop was hanging in the Mutex. I looked for your code and found a misuse of the mutex.  You mixed different Calls with the same ground Mutex, was isn't allowed the xSemaphoreCreateRecursiveMutex() needs a different ground mutex as the simple one. I changed all to xSemaphoreCreateRecursiveMutex() now it workes fine. But I have not made extensive tests. Have a look to the mutex use if you have time.
Best Regards
       Andreas

**Comment by schreibfaul1** [comment]
Hello Andreas,
thank you for your detailed explanation. The mutex should prevent two tasks from executing a function at the same time. This will soon be corrected in the master.
Best regards
Wolle
