### ISSUE TITLE
Problem with void audio_showstreamtitle(const char* info)

### ISSUE THREAD

**Issue by Arielhh** [schreibfaul1/ESP32-audioI2S#765]
I am using the void audio_showstreamtitle(const char* info) but when switching to a station that doesn't provide that info the info of the previous station is keep showing. Is there an option to reset  the audio_showstreamtitle(const char* info) when switching to a different station that doesn't provide that info?
Thanks

**Comment by Arielhh** [comment]
solved it myself :)

**Comment by jeromepar** [comment]
may we ask what the problem was?
thx
