### ISSUE TITLE
Compatibility with Arduino Core 3.0.1

### ISSUE THREAD

**Issue by kungfupizza** [schreibfaul1/ESP32-audioI2S#767]
ESP32 Arduino Core 3.0.1 has recently come up. Is this library compatible with the same?

**Comment by tueddy** [comment]
I successfully compiled the library in PlatformIO with Arduino 3.0.1. 
Sound also came out of the speaker, so the answer is yes.
@kungfupizza So there is no reason not to try it yourself..

**Comment by kungfupizza** [comment]
Thank you for confirmation. I did try and I could play audio from SD card but not from HOST. Has that worked for you ? @tueddy

**Comment by cziter15** [comment]
I have auto-cpu scaling done in my project for Mp3 playing (jumping from 80M to 240) and it seems that audio plays too fast.

**Comment by jonnybergdahl** [comment]
Compiling the internalDAC.ino file with ESP32 Arduino Core 3.0.4 gives the following compile error. 
```
Compilation error: 'I2S_DAC_CHANNEL_BOTH_EN' was not declared in this scope
```

**Comment by cziter15** [comment]
> Compiling the internalDAC.ino file with ESP32 Arduino Core 3.0.4 gives the following compile error.
> 
> ```
> Compilation error: 'I2S_DAC_CHANNEL_BOTH_EN' was not declared in this scope
> ```

This flag does not exist on 3.x

The constructor definition is:
`Audio(bool internalDAC = false, uint8_t channelEnabled = 3, uint8_t i2sPort = I2S_NUM_0); // #99`

**Comment by schreibfaul1** [comment]
In Arduino V3, IDF V5.1 runs in the background. Unfortunately this version does not recognize an internal DAC regarding I2S. The latest version that supports the internal DAC is Arduino 2.0.17
