### ISSUE TITLE
Web radio request failed

### ISSUE THREAD

**Issue by ChassaB** [schreibfaul1/ESP32-audioI2S#768]
Thanks for the great library. Having fun with it. Running happily on an LOLIN S3.
With the web radio sketch I have tried connecting to many of the stations and nearly always get a request failed in the info messages. See attached.

Setting  audio.setConnectionTimeout (500, 3000); seems to fix it for most of them. Is this the right way to fix it or is there something else?
![web radio error](https://github.com/schreibfaul1/ESP32-audioI2S/assets/17804553/9cc8b144-d1b9-4ef6-acb7-7508c90c640f)

**Comment by schreibfaul1** [comment]
I can't say exactly what happens in the mbedtls area, but 4.6s for an SSL connection is too long. Could it be that the system clock is not 240MHz?

**Comment by ChassaB** [comment]
Here are my Arduino IDE settings. I'm in Australia, not that that should make that much difference.
![Uploading Screenshot 2024-06-15 at 8.28.48 AM.png…]()

**Comment by ChassaB** [comment]
Here are my IDE settings. Not sure why it should take so long even if I am in Australia.
![Screenshot 2024-06-15 at 8 34 40 AM](https://github.com/schreibfaul1/ESP32-audioI2S/assets/17804553/b74f790d-575b-4568-a9e4-551ac00772e8)
