### ISSUE TITLE
3+1 small improvement

### ISSUE THREAD

**Issue by BCsabaEngine** [schreibfaul1/ESP32-audioI2S#77]
Hallo/hello!

I am so happy to use your library. I have found some improvement to play short (3-20sec) mp3s from http(s) host.

1. `m_metaline="";` in reset() function or in .h file should be `m_metaline.reserve(100); m_metaline="";` because String operations may be slow when reallocating space when adding bytes by bytes.
2. There is a "fake" `delay(1000)` at line 1450, this would be configurable or shorter (my measurement is **50ms is enought**)
3. In example file `loop() { audio.loop(); }` can be easier like this: `loop() { audio.loop(); if (!audio.isRunning()) delay(5); }`
4. `Contnent-Length` should be `Content-Length` 

Can you implement (pull) it to source? Thx!
Best regards!

**Comment by schreibfaul1** [comment]
Thank you very much!
