### ISSUE TITLE
Cannot use any other instance of WiFiClientSecure or ESP-IDF's esp_http_client

### ISSUE THREAD

**Issue by kungfupizza** [schreibfaul1/ESP32-audioI2S#773]
I am using esp32-arduino 3.0.1(latest) as component in my ESP-IDF project. When audio is initialized, I cannot use another instance of WiFiClientSecure in the project or even ESP-IDF's esp_http_client instance.
The client connects but gets stuck on sending.

NOTE: Also tried to roll back to esp32-arduino v2.0.17 but saw similar issues..

**Comment by schreibfaul1** [comment]
This could be related to:
https://github.com/platformio/platform-espressif32/issues/1225#issuecomment-2176058619

**Comment by BenjaminMickler** [comment]
I have this issue too.
