### ISSUE TITLE
[ESP32S3 3.0.1] Too fast / high pitch playing - text to speech / google

### ISSUE THREAD

**Issue by cziter15** [schreibfaul1/ESP32-audioI2S#774]
Hello,

I've encountered an issue with TTS on my custom board with ESP32S3 and MAX9835A.

When TTS request is issued, the audio plays too fast and with higher pitch.
Other things like playing from stream or filesystem aren't impacted by the issue.

I'm using 3.0.1 Arduino core.

Can anyone try to reproduce this? Just try to play TTS (connecttospeech)

**Comment by x9prototype** [comment]
I have the same boards and same core, and am experiencing the same issue

**Comment by cziter15** [comment]
@schreibfaul1 you've referenced a commit that is targeting internal DAC, while this issue is targeting MAX9835A (external DAC)

**Comment by cziter15** [comment]
@schreibfaul1 using latest master 0a1674329449581a70c8e8ca7fff0e406b23d820 and still experiencing the issue

**Comment by NewoPL** [comment]
I verified that last commit 0a1674329449581a70c8e8ca7fff0e406b23d820 completly distorts the audio from google TTS mp3 
[home.zip](https://github.com/user-attachments/files/16045156/home.zip)

**Comment by cziter15** [comment]
This issue is related to bps. I've tried streaming mp3 with various bitrates and everything below 128 was affected.

**Comment by msw1998** [comment]
Any fix for this issue?

**Comment by cziter15** [comment]
@schreibfaul1 any ideas where to look?

**Comment by cziter15** [comment]
This issue seems to be fixed
