### ISSUE TITLE
AUDIO PCM OVER UDP

### ISSUE THREAD

**Issue by AntonioRiccelli77** [schreibfaul1/ESP32-audioI2S#775]
Hi 
first of all congratulations for your work on I2S.
Would you have a simple example to start from to reproduce via a PCM5102 the flow of an 8bit, 8Khz mono, telephone quality stream transmitted on a UDP port. Basically I have to take the samples from the UPD receive buffer and forward them via I2S to the PCM5102.
Thanks
AR

**Comment by schreibfaul1** [comment]
I have little experience with UDP. Maybe the WiFiClient can be replaced by WiFiUDP?
