### ISSUE TITLE
Compilation error in Arduino running 2.3.2

### ISSUE THREAD

**Issue by fusionliquid** [schreibfaul1/ESP32-audioI2S#779]
I used to have no problem using it, but recently after upgrade, all the codes with this audio library resulted in error below 

/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp: In function 'int vorbis_dsp_pcmout(int16_t*, int)':
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3023:85: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
 3023 |                                 s_dsp_state->lW, s_dsp_state->W, s_dsp_state->work[i],
      |                                                                  ~~~~~~~~~~~~~~~~~~~^
      |                                                                                     |
      |                                                                                     int32_t* {aka long int*}
In file included from /Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:23:
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.h:264:62: note:   initializing argument 5 of 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)'
  264 | void     mdct_unroll_lap(int n0, int n1, int lW, int W, int *in, int *right, const int *w0, const int *w1, short int *out,
      |                                                         ~~~~~^~
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3024:57: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
 3024 |                                 s_dsp_state->mdctright[i], _vorbis_window(s_blocksizes[0] >> 1),
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~^
      |                                                         |
      |                                                         int32_t* {aka long int*}
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.h:264:71: note:   initializing argument 6 of 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)'
  264 | void     mdct_unroll_lap(int n0, int n1, int lW, int W, int *in, int *right, const int *w0, const int *w1, short int *out,
      |                                                                  ~~~~~^~~~~
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3024:74: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'const int*' [-fpermissive]
 3024 |                                 s_dsp_state->mdctright[i], _vorbis_window(s_blocksizes[0] >> 1),
      |                                                            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                                                          |
      |                                                                          int32_t* {aka long int*}
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.h:264:89: note:   initializing argument 7 of 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)'
  264 | void     mdct_unroll_lap(int n0, int n1, int lW, int W, int *in, int *right, const int *w0, const int *w1, short int *out,
      |                                                                              ~~~~~~~~~~~^~
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3025:47: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'const int*' [-fpermissive]
 3025 |                                 _vorbis_window(s_blocksizes[1] >> 1),
      |                                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               int32_t* {aka long int*}
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.h:264:104: note:   initializing argument 8 of 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)'
  264 | void     mdct_unroll_lap(int n0, int n1, int lW, int W, int *in, int *right, const int *w0, const int *w1, short int *out,
      |                                                                                             ~~~~~~~~~~~^~
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp: In function 'void mdct_unroll_lap(int, int, int, int, int*, int*, const int*, const int*, short int*, int, int, int)':
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3062:27: error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]
 3062 |     int32_t       *l = in + (W && lW ? n1 >> 1 : n0 >> 1);
      |                        ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           int*
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3063:30: error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]
 3063 |     int32_t       *r = right + (lW ? n1 >> 2 : n0 >> 2);
      |                        ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              int*
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3065:34: error: invalid conversion from 'const int*' to 'const int32_t*' {aka 'const long int*'} [-fpermissive]
 3065 |     const int32_t *wR = (W && lW ? w1 + (n1 >> 1) : w0 + (n0 >> 1));
      |                         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  |
      |                                  const int*
/Users/Documents/Arduino/libraries/ESP32-audioI2S-master/src/vorbis_decoder/vorbis_decoder.cpp:3066:34: error: invalid conversion from 'const int*' to 'const int32_t*' {aka 'const long int*'} [-fpermissive]
 3066 |     const int32_t *wL = (W && lW ? w1 : w0);
      |                         ~~~~~~~~~^~~~~~~~~~
      |                                  |
      |                                  const int*
Multiple libraries were found for "SD.h"
  Used: /Users/Library/Arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/SD
  Not used: /Users/Library/Arduino15/libraries/SD
Multiple libraries were found for "Audio.h"
  Used: /Users/Documents/Arduino/libraries/ESP32-audioI2S-master
  Not used: /Users/Documents/Arduino/libraries/Audio
exit status 1

Compilation error: exit status 1

**Comment by mifarelight** [comment]
I tried to changed the PlatformIO configuation in platformio.ini to solve this problem.

from (**Stable** version)

```
platform = espressif32
```

to (**Development** version)

```
platform = https://github.com/platformio/platform-espressif32.git
```

---

It used other version toolchains

```
  - framework-arduinoespressif32 @ 3.20017.0 (2.0.17)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
```

rather than

```
 - framework-arduinoespressif32 @ 3.1.0
 - framework-arduinoespressif32-libs @ 5.3.0+sha.466a392a76
 - tool-esptoolpy @ 4.7.5
 - tool-mklittlefs @ 3.2.0
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208
 - toolchain-riscv32-esp @ 13.2.0+20240530
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
```
