### ISSUE TITLE
frying noise

### ISSUE THREAD

**Issue by lidense** [schreibfaul1/ESP32-audioI2S#784]
I have made a webradio using this library.
It works very well with Adafruit feather S3 while using a lolin S3 wroom I hear a very fine frying noise, like very find crackling when sound is heard, not when it is silent. Any idea?

**Comment by lidense** [comment]
I'm using a UDA1334A.
Regards

**Comment by kungfupizza** [comment]
I had similar issues when I used PINs 0, 1, 2 on ESP32S3. Also could bue due to tangled wires and interference.

**Comment by Arielhh** [comment]
sounds like a grounding issue

**Comment by KartoffelToby** [comment]
had this issue to with MAX98357 and ESP32 S3, even on other pins

**Comment by Arielhh** [comment]
Remove the 2 capacitors on the output stage. Remove also the 2 ferrites on the output stage and replace them with solder short. This will eliminate that noise.

**Comment by KartoffelToby** [comment]
@Arielhh thanks for the replying, have you any Pictures of this mod?

I found a other solution, but it still have some noise.

I found the main noise is gone when i connect it to 3,3v on the ESP not 5v direct.

And also make sure if your playing from a SD card its connected via SD_MMC, lack of speed produce noise too

**Comment by Arielhh** [comment]
> @Arielhh thanks for the replying, have you any Pictures of this mod?
> 
> I found a other solution, but it still have some noise.
> 
> I found the main noise is gone when i connect it to 3,3v on the ESP not 5v direct.
> 
> And also make sure if your playing from a SD card its connected via SD_MMC, lack of speed produce noise too

send me a photo of your sound module and i will poit you to the right components.
You can also try putting a large electrolytic capacitor  (~470uf or higher)  on the 5V close to the amplifier module.

**Comment by KartoffelToby** [comment]
@Arielhh sure no problem, here is a Picture ![adafruit_products_pinouts.jpg](https://github.com/user-attachments/assets/dd4eedfb-2fab-48b0-acca-522facd0bfc2)

**Comment by Arielhh** [comment]
There are 4 components on the top of the photo.
The two from both out sides left and right are capacitors connected to the ground - remove them
The two middle ones are ferrite remove them and instead replace each one with a short
You can have a look at the electronic schematic provided by Adafruit. 
These are supposed to act as filters but if you look with an oscilloscope you will see they are generation some noise instead of filtering it.
