### ISSUE TITLE
new 3.012 

### ISSUE THREAD

**Issue by stef-ladefense** [schreibfaul1/ESP32-audioI2S#796]
hi,

the latest version 3.012 contains version 3.012e and not 3.012f.
is this normal?

thank,

Stef

**Comment by schreibfaul1** [comment]
hi, I rarely create tags, usually after a major change. 
For the very latest version, the only option is to update via Git.

**Comment by stef-ladefense** [comment]
thank you
i like this library, i use it to give new life to a 10 year old obsolete web radio. (thanks Orange) by changing its heart.

currently i store the url, the name and a jpg per station line.
does this information exist in the stream?
Is there a way to retrieve the name of the station, its logo, or see information on the title or program directly from the stream (like on DAB)?
