### ISSUE TITLE
128k Bitrate

### ISSUE THREAD

**Issue by Quirin9** [schreibfaul1/ESP32-audioI2S#8]
If I want to play a mp3 file with 128k bitrate it wont play. Do I need to set the bitrate anywhere?

**Comment by schreibfaul1** [comment]
Hello Quirin9,
http://mp3.ffh.de/radioffh/hqlivestream.mp3 will work without drops
![image](https://user-images.githubusercontent.com/26044260/64191243-580aa200-ce78-11e9-9e52-2f04e3e7d861.png)
The bitrate will internally recognised, no settings are needed. 192K works also, 320k from case to case
