### ISSUE TITLE
Get audio waveform to output on LED VU meter?

### ISSUE THREAD

**Issue by NonaSuomy** [schreibfaul1/ESP32-audioI2S#80]
Is there a way to get the audio waveform data to output on an LED VU meter?

**Comment by CelliesProjects** [comment]
Check https://github.com/kosme/arduinoFFT

**Comment by NonaSuomy** [comment]
Looks great! Is there a way to do it without the microphone and take sound samples direct from your audioI2S library?

**Comment by marcelstoer** [comment]
More inspiration: https://blog.squix.org/2020/12/esp32-adding-a-spectrum-analyzer-to-bluetooth-audio.html
