### ISSUE TITLE
text section exceeds available space in board?

### ISSUE THREAD

**Issue by hzkincony** [schreibfaul1/ESP32-audioI2S#811]
i use ESP32-S3 N16R8 , but when i compile, it showed:
Sketch uses 1340981 bytes (102%) of program storage space. Maximum is 1310720 bytes.
text section exceeds available space in board
Global variables use 46284 bytes (14%) of dynamic memory, leaving 281396 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
Error compiling for board ESP32S3 Dev Module.

how to solve? thanks

**Comment by schreibfaul1** [comment]
You have 16MB flash, which is still plenty of space. The easiest method is to change the partition table. You can use "Huge App".

**Comment by skylai82** [comment]
![image](https://github.com/user-attachments/assets/31694b64-9a57-41c4-b67d-a7fbbc76f836)
How to reduce Audio.h space?

**Comment by skylai82** [comment]
> ![image](https://private-user-images.githubusercontent.com/37041202/369313095-31694b64-9a57-41c4-b67d-a7fbbc76f836.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTg1MzUsIm5iZiI6MTcyNjgxODIzNSwicGF0aCI6Ii8zNzA0MTIwMi8zNjkzMTMwOTUtMzE2OTRiNjQtOWE1Ny00MWM0LWI2N2QtYTdmYmJjNzZmODM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3NDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NDg5ZjdjY2UxYzc3MDQ1ODgzMjQ5Y2VjOGM3Y2I4OTRlZTc3YjhlNmRlZmJlODQ3YWM2ZjhhMTUzY2FiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hXeyOyjTXKb6A8Gv60tP9EyNqHtLuoZwOu3-N4wboD0) How to reduce Audio.h space?

![image](https://github.com/user-attachments/assets/43e07dad-487d-44f8-8685-eaa52c7f26ac)
Can I edit my partition scheme?
