### ISSUE TITLE
WEB SOCKET WEBSOCKET

### ISSUE THREAD

**Issue by akdeb** [schreibfaul1/ESP32-audioI2S#814]
Hi there,
This library is epic. Does it work for a full-duplex web socket implementation? I want my ESP32 to act as a client and connect to a websocket WS server (that returns audio to the client). I want to use the ESP32-audioI2S library to connect to the WS and write to the I2S

**Comment by schreibfaul1** [comment]
Yes, you can do this via websocket or classically as an HTTP GET request.
This is done in the [ESPUino](https://github.com/schreibfaul1/ESP32-MiniWebRadio) project.
