### ISSUE TITLE
compilation error using the library  shows error related to memory.h

### ISSUE THREAD

**Issue by mayur9095** [schreibfaul1/ESP32-audioI2S#815]
when i try to compile any program shows library error which i have given below :

C:\Users\Lenovo\Documents\Arduino\libraries\ESP32-audioI2S-master\src\aac_decoder\libfaad/neaacdec.h:40:20: fatal error: memory.h: No such file or directory

compilation terminated.

**Comment by schreibfaul1** [comment]
Strange, but the functions calloc/malloc are also provided differently. <memory.h> is not really needed, you can delete the entry</memory.h>
