### ISSUE TITLE
slow stream, dropouts are possible

### ISSUE THREAD

**Issue by lidense** [schreibfaul1/ESP32-audioI2S#828]
I have made a webradio which works well with this library for most stations using my wifi. But if I am on the move and want to use a wifi hotspot using my 4G phone I get "slow stream, dropouts are possible". 
I tried the wifihighthruput version which uses Arduino as a component but does not work very well (see previous posts).
Any other solution?

**Comment by schreibfaul1** [comment]
In any case, no improvement is possible with the pre-compiled Arduino version. I have quite good experience with Arduino as a component. But I am not a WiFi/LWIP expert, the settings in menuconfig may not be optimal. But you have the option of testing your own settings.

**Comment by lidense** [comment]
OK thanks for your feedback.

**Comment by lidense** [comment]
Hi I still have problems when connecting via my wifi hostpot, I get "slow stream, dropouts are possible" and no sound from my webradio buikt with this library while it works fine with my home wifi router. I remember of an option of using Arduino as a component and using some special settings but cannot find any example on that, can you please help? Thanks

**Comment by schreibfaul1** [comment]
You can start by sending a ping to the host. If the response time is > 100 ms, it will be difficult.
Otherwise, you can use this template, which the sdkconfig is already optimised.
https://github.com/schreibfaul1/ESP32_Arduino_ESPIDF

**Comment by lidense** [comment]
Thank-you for your prompt answer. I will try. 
Best Regards

**Comment by lidense** [comment]
ping takes 75 to 200 ms depending on the moment. I looked at the code of the commit allowing to modify sdkconfig. What do I have to do to adapt it to my project? Do I have to import all my platformio files and I2S esp32 into this template?

**Comment by lidense** [comment]
ping takes 75 to 200 ms depending on the moment. I looked at the code of the commit allowing to modify sdkconfig. What do I have to do to adapt it to my project? Do I have to import all my platformio files and I2S esp32 into this template?
