### ISSUE TITLE
Compilatio error: invalid conversion from 'uint32_t*' {aka 'unsigned int*'} to 'long unsigned int*' [-fpermissive]

### ISSUE THREAD

**Issue by FatherMarco1971** [schreibfaul1/ESP32-audioI2S#842]
![image](https://github.com/user-attachments/assets/92d6c8f4-b9fb-4a35-904f-c0a8594ebd75)

Using last release i've thos errors compiling?
I can't understand why...

Could you help?

**Comment by schreibfaul1** [comment]
I had recently upgraded the AAC decoder. With the Arduino version 3.0.4 I did not notice the errors. Now I have replaced the "unsigned long" with "uint32_t". It also works with version 2.0.17 or similar.
