### ISSUE TITLE
In the latest git version, there is a strange stuttering when playing a stream.

### ISSUE THREAD

**Issue by genicsoft** [schreibfaul1/ESP32-audioI2S#851]
In the latest git version, there is a strange stuttering when playing a stream. I did not experience this problem with version 0.12.
I have reverted to 0.12

But some streaming media is fine.

**Comment by schreibfaul1** [comment]
It may be that there are files or streams that behave like this. Do you have a file or URL that I can use to test this?

**Comment by cziter15** [comment]
@schreibfaul1 
> It may be that there are files or streams that behave like this. Do you have a file or URL that I can use to test this?

I have same issue when using polish audio TTS (google).

**Comment by SlavaZagaynov** [comment]
вчера мучался с заиканием  TTS (google). Если прошивать esp32 не на 240 мгц, а на 160 - то не заикается.

**Comment by cziter15** [comment]
> Вчера мучался с заиканием TTS (google). Если прошивать esp32 не на 240 мгц, а на 160 - то не заикается.

> @SlavaZagaynov said: Yesterday I was struggling with stuttering TTS (google). If you flash esp32 not at 240 MHz, but at 160 - then it does not stutter.

Looks like you wanted to say CPU frequency, not flash frequency.
In my project I have implemented dynamic frequency boost. Normally my device acts as zigbee releay @ 80MHz.
When MQTT receives notification request (TTS) it bumps the clock to 240M and it has stuttering with polish language.
No issues with english TTS. Also no issues with MP3 stream, like web-radio.

**Comment by SlavaZagaynov** [comment]
![image](https://github.com/user-attachments/assets/e7c8e227-8294-4137-973d-6a28b28e2dd8)

Я еще не закончил мои эксперименты. 
Пока лучший вариант без заикания TTS при такой установке.
(извините, я не знаю английский).

**Comment by XylenC4** [comment]
Had the same issue with playing MP3s on a ESP32S3 without PSRAM using SD and SD_MMC (4-Bit mode) using the example I2Saudio, playing a stream was working fine. I've now changed back to the lastest stable and the stottering dissaperared.

**Comment by schreibfaul1** [comment]
Under certain conditions, tasks may not get the necessary computing time. the Audio.loop() does not have to be called all the time. what if you insert a delay (1...20ms)?
````
void loop(){
    audio.loop();
    vTaskDelay(1);
}
````
