### ISSUE TITLE
Can you help me write the code to call Doubao TTS?

### ISSUE THREAD

**Issue by Explorerlowi** [schreibfaul1/ESP32-audioI2S#856]
My programming skills are so poor that I really can’t do it (灬ꈍ ꈍ灬).
Here is the relevant document: https://www.volcengine.com/docs/6561/79823
I will pay you a certain amount of compensation. Thank you very much if you can do it!

**Comment by Explorerlowi** [comment]
The content returned by Doubao TTS request is not directly a binary audio stream. Its audio data is stored in the data field of a json structure. It is base64 encoded data. Binary audio data can only be obtained after base64 decoding. In this case, how to play it
![5227de0688c11667cb49d6be8e00967d](https://github.com/user-attachments/assets/2cbd0366-7e91-4ae1-bb55-504d72e6059a)
![image](https://github.com/user-attachments/assets/5fbeaeca-09b6-4562-99a2-180f168cbf9e)

**Comment by schreibfaul1** [comment]
With a "normal audio stream", the data would be written to the buffer here.
InBuff.getWritePtr() is the pointer to the position from which the data is written
bytesAddedToBuffer contains the number of bytes actually written.
Then the conversion from base64 would have to be done.
![image](https://github.com/user-attachments/assets/d04daa79-5a51-438d-b9fe-c30c5a616034)

You don't need to worry about the rest, if it is an MP3 stream, for example, the ID3 header is automatically loaded when the buffer is full enough and the file is played.
