### ISSUE TITLE
esp32 wroom play online mp3 no sounds.

### ISSUE THREAD

**Issue by splm** [schreibfaul1/ESP32-audioI2S#871]
Hello,everyone:
I use ESP32 wroom32e to connect with the MAX98357, and have connected the speaker, but there has been no sound, it has been bothered for a long time, please what will be the reason, thank you.

The following figure is as follows,
![image](https://github.com/user-attachments/assets/0f1df0ef-ccf6-4e8e-9be7-0d3c286e2c09)
![image](https://github.com/user-attachments/assets/fa23968b-a3f7-4578-a8a8-c714a33385a0)

--------
#define I2S_DOUT      25
#define I2S_BCLK      27
#define I2S_LRC       26

const char *url = "http://downsc.chinaz.net/Files/DownLoad/sound1/201906/11582.mp3";
void setup(){
    play();
}
void play(){
  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT); 
  audio.setVolume(21); 
  audio.connecttohost(url); 
}
void loop(){
    audio.loop();
}

**Comment by vednildip** [comment]
[README]
ESP32-audioI2S
⚠️ This library only works on multi-core ESP32 chips like the ESP32-S3. It does not work on the ESP32-S2 or the ESP32-C3 ⚠️
