### ISSUE TITLE
在播放某些网络流的时候出现HTTP 400 Bad Request。

### ISSUE THREAD

**Issue by caiyy** [schreibfaul1/ESP32-audioI2S#881]
Url:
http://pal.caiyy.cn:28555/Music/EB高梦博-中国嘻哈榜-Life Is Still a Struggle-2013.mp3
http://pal.caiyy.cn:28555/Music/A-Hi-Fi Serious-Starbucks-2002.flac
http://pal.caiyy.cn:28555/Music/Adam Lambert-For Your Entertainment-Whataya Want from Me-2009.flac
http://pal.caiyy.cn:28555/Music/罗明玥/执子之手 - 宝石Gem 哩哩.flac

很早以前的版本没有这样的错误、

info        buffers freed, free Heap: 175364 bytes
info        connect to: "pal.caiyy.cn" on port 28555 path "/Music/EB高梦博-中国嘻哈榜-Life Is Still a Struggle-2013.mp3"
info        Connection has been established in 26 ms, free Heap: 174760 bytes
streamtitle HTTP/1.1 400 Bad Request
station     
icyurl

**Comment by schreibfaul1** [comment]
Spaces should not appear in a URL. But some browsers replace these with "%20", which I have now also switched on.

**Comment by caiyy** [comment]
@schreibfaul1   谢谢大佬、🙇‍
