### ISSUE TITLE
持续播放音乐的时候出现的问题、

### ISSUE THREAD

**Issue by caiyy** [schreibfaul1/ESP32-audioI2S#882]
url:
[http://pal.caiyy.cn:28555/Music/罗明玥/执子之手 - 宝石Gem 哩哩.flac](url)

log:

12:06:33.884 -> Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception). 
12:06:33.884 -> Debug exception reason: BREAK instr 
12:06:33.916 -> Core  0 register dump:
12:06:33.916 -> PC      : 0x40085ddc  PS      : 0x00000016  A0      : 0x40080306  A1      : 0x3ffc88c0  
12:06:33.916 -> A2      : 0x3ffc552c  A3      : 0x00000000  A4      : 0x00100590  A5      : 0x3ffc88f0  
12:06:33.916 -> A6      : 0x00000000  A7      : 0x3ffc8484  A8      : 0x00000000  A9      : 0x00000000  
12:06:33.916 -> A10     : 0x0000000c  A11     : 0x00001000  A12     : 0x70000005  A13     : 0x00000000  
12:06:33.948 -> A14     : 0xfffbfff0  A15     : 0x3ffc64e4  SAR     : 0x00000008  EXCCAUSE: 0x00000001  
12:06:33.948 -> EXCVADDR: 0xdc5fa257  LBEG    : 0x4008b138  LEND    : 0x4008b14e  LCOUNT  : 0xffffffff  
12:06:33.948 -> 
12:06:33.948 -> 
12:06:33.948 -> Backtrace: 0x40085dd9:0x3ffc88c0 0x40080303:0x3ffc88f0 0x65a5a5a2:0xa5a5a5a5 |<-CORRUPTED
12:06:33.948 -> 
12:06:33.948 -> 
12:06:33.948 -> 
12:06:33.948 -> 
12:06:33.948 -> ELF file SHA256: abfb1d306
12:06:33.948 -> 
12:06:33.948 -> Re-entered core dump! Exception happened during core dump!
12:06:33.980 -> Rebooting...
12:06:33.980 -> ets Jul 29 2019 12:21:46
12:06:33.980 -> 
12:06:33.980 -> rst:0xc (SW_CPU_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
12:06:33.980 -> configsip: 0, SPIWP:0xee
12:06:33.980 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
12:06:33.980 -> mode:DIO, clock div:1
12:06:33.980 -> load:0x3fff0030,len:4916
12:06:33.980 -> load:0x40078000,len:16436
12:06:33.980 -> load:0x40080400,len:4
12:06:33.980 -> ho 8 tail 4 room 4
12:06:33.980 -> load:0x40080404,len:3524
12:06:34.023 -> entry 0x400805b8
12:06:34.944 -> 
12:06:34.944 -> Reset
12:06:34.944 -> Free mem=240844

**Comment by vednildip** [comment]
[README]
ESP32-audioI2S
⚠️ This library only works on multi-core ESP32 chips like the ESP32-S3. It does not work on the ESP32-S2 or the ESP32-C3 ⚠️
