### ISSUE TITLE
小米手机自带的音乐文件怎么发送到DLNA

### ISSUE THREAD

**Issue by 1359450511** [schreibfaul1/ESP32-audioI2S#903]
就是如何进行DLNA播放，就像手机上的视频可以推送到电视机播放一样，手机的音乐怎么通过DLNA推送到ESP32-I2S audio

**Comment by schreibfaul1** [comment]
Exactly, if the URL is known, a song can be played from a DLNA server.
You can find out the URL with the VLC Player.
![image](https://github.com/user-attachments/assets/36f763b3-f0a4-449e-88c4-f3ba1e019cb6)
Or you can use a library to display the contents of the DLNA https://github.com/yellobyte/SoapESP32

**Comment by foorschtbar** [comment]
> 就是如何进行DLNA播放，就像手机上的视频可以推送到电视机播放一样，手机的音乐怎么通过DLNA推送到ESP32-I2S audio

if the issue were in english, then others with the same question would also benefit...

**Comment by schreibfaul1** [comment]
This library requires a valid URL. The URL can be found out with the VLC Player, as I have described. To use the full DLNA functionality (title, album genre...) another library like the one from Yellbyte is required.
