### ISSUE TITLE
a2dp source

### ISSUE THREAD

**Issue by fmkkaya** [schreibfaul1/ESP32-audioI2S#914]
Hello, is it possible to write data to the bluetooth headset with BluetoothA2DPSource  at the same time as i2s write?

**Comment by schreibfaul1** [comment]
Yes, this is possible, but only with the ESP32, the ESP32-S3 is not suitable for this.
There is an interface for the I2S stream:
`audio_process_i2s((int16_t*)m_outBuff, m_validSamples, 16, 2, &continueI2S);`
And there is, for example, the [ESPUino](https://github.com/biologist79/ESPuino) project, which uses this for BT headphones and speakers.
